import { MCP_CONNECT } from "@/content/launch";
import type { KitResource } from "@/lib/kits";

const KIT = `${MCP_CONNECT.baseUrl}/kits/credit/morpho`;
const LIQUIDITY_KIT = `${MCP_CONNECT.baseUrl}/kits/liquidity/morpho`;
const SKILLS = "https://github.com/morpho-org/morpho-skills/blob/main/plugins/morpho-builder/skills";
const SKILLS_RAW =
  "https://raw.githubusercontent.com/morpho-org/morpho-skills/main/plugins/morpho-builder/skills";
const DOCS = "https://docs.morpho.org";

/** The two liquidity vault shapes. They reuse the vault half of this family. */
const VAULT_SHAPES = ["liquidity_allocator", "permissioned_vault"] as const;
const LENDING = ["curated_vault", "embedded_earn", "collateral_loans"] as const;
const LENDING_AND_VAULTS = [...LENDING, ...VAULT_SHAPES] as const;
const BORROW_SIDE = ["collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield"] as const;
const VAULT_SIDE = ["curated_vault", "embedded_earn", ...VAULT_SHAPES] as const;
/** Runs or configures a Vault V2. */
const CURATOR_SIDE = ["curated_vault", ...VAULT_SHAPES] as const;

/**
 * Morpho family. Every Morpho docs page also serves raw markdown at the same
 * URL with ".md" appended, which is what rawHref carries. Since M34 the
 * vault half serves the Liquidity sector too (VAULT_SHAPES), which is where
 * the two sectors overlap. Ids are immutable.
 */
export const MORPHO_RESOURCES: readonly KitResource[] = [
  // -- agent skills ---------------------------------------------------------
  {
    id: "morpho.skill-earn",
    family: "morpho",
    title: "Earn integration skill",
    kind: "skill",
    href: `${SKILLS}/earn-integration/SKILL.md`,
    rawHref: `${SKILLS_RAW}/earn-integration/SKILL.md`,
    why: "Step-by-step instructions written for a coding agent that is building deposits, withdrawals, positions, APY and safety copy on a vault.",
    shapes: VAULT_SIDE,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 1,
  },
  {
    id: "morpho.skill-earn-vault-v2",
    family: "morpho",
    title: "Vault V2 implementation reference",
    kind: "skill",
    href: `${SKILLS}/earn-integration/references/vault-v2.md`,
    rawHref: `${SKILLS_RAW}/earn-integration/references/vault-v2.md`,
    why: "The dense version of everything the earn skill assumes, from data sources to ERC-4626 quirks to release checks.",
    shapes: VAULT_SIDE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 2,
  },
  {
    id: "morpho.skill-earn-review",
    family: "morpho",
    title: "Earn pre-launch review",
    kind: "checklist",
    href: `${SKILLS}/earn-integration/references/review.md`,
    rawHref: `${SKILLS_RAW}/earn-integration/references/review.md`,
    why: "Eight review passes with evidence requirements, covering wording, disclosure, rate display, math and safety before anything ships.",
    shapes: VAULT_SIDE,
    steps: ["security", "review"],
    priority: "recommended",
  },
  {
    id: "morpho.skill-earn-checkers",
    family: "morpho",
    title: "Earn compliance checkers",
    kind: "checklist",
    href: `${SKILLS}/earn-integration/references/checkers`,
    why: "One file per review pass so an agent can run vocabulary, disclosure, rate transparency, conversion, math and safety checks separately.",
    shapes: VAULT_SIDE,
    steps: ["security", "review"],
    priority: "recommended",
  },
  {
    id: "morpho.skill-borrow",
    family: "morpho",
    title: "Borrow integration skill",
    kind: "skill",
    href: `${SKILLS}/borrow-integration/SKILL.md`,
    rawHref: `${SKILLS_RAW}/borrow-integration/SKILL.md`,
    why: "Agent instructions for market discovery, collateral, borrowing, repayment, health, liquidity and refinancing.",
    shapes: BORROW_SIDE,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 1,
  },
  {
    id: "morpho.skill-borrow-blue",
    family: "morpho",
    title: "Variable-rate market reference",
    kind: "skill",
    href: `${SKILLS}/borrow-integration/references/blue.md`,
    rawHref: `${SKILLS_RAW}/borrow-integration/references/blue.md`,
    why: "The single most useful file for a variable-rate borrowing product on isolated markets.",
    shapes: BORROW_SIDE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 2,
  },
  {
    id: "morpho.skill-borrow-midnight",
    family: "morpho",
    title: "Fixed-term market reference",
    kind: "skill",
    href: `${SKILLS}/borrow-integration/references/midnight.md`,
    rawHref: `${SKILLS_RAW}/borrow-integration/references/midnight.md`,
    why: "Fixed-rate, fixed-term borrowing with quotes, maturities and secondary exits. Useful thinking even where the fixed-rate contracts are not deployed.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "morpho.skill-borrow-review",
    family: "morpho",
    title: "Borrow pre-launch review",
    kind: "checklist",
    href: `${SKILLS}/borrow-integration/references/review.md`,
    rawHref: `${SKILLS_RAW}/borrow-integration/references/review.md`,
    why: "The review workflow for borrowing integrations, with the same evidence discipline as the earn review.",
    shapes: BORROW_SIDE,
    steps: ["security", "review"],
    priority: "recommended",
  },
  {
    id: "morpho.skills-repo",
    family: "morpho",
    title: "Morpho skills repository",
    kind: "repo",
    href: "https://github.com/morpho-org/morpho-skills",
    why: "Install the whole plugin into Claude Code or Cursor instead of pasting files one at a time.",
    shapes: LENDING_AND_VAULTS,
    steps: ["basics"],
    priority: "recommended",
  },

  // -- machine-readable docs, MCP, SDK, API ------------------------------------
  {
    id: "morpho.llms",
    family: "morpho",
    title: "Morpho docs for agents (llms.txt)",
    kind: "docs",
    href: `${DOCS}/llms.txt`,
    rawHref: `${DOCS}/llms-full.txt`,
    why: "An index of every docs page plus the whole corpus as one markdown file. Point your agent here before it guesses.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 3,
  },
  {
    id: "morpho.mcp",
    family: "morpho",
    title: "Morpho MCP server",
    kind: "tool",
    href: `${DOCS}/developers/agents/mcp`,
    rawHref: `${DOCS}/developers/agents/mcp.md`,
    why: "Lets your agent query live vaults, markets and positions and prepare unsigned transactions. Experimental, so not a production dependency.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.sdk",
    family: "morpho",
    title: "Morpho SDK",
    kind: "docs",
    href: `${DOCS}/developers/sdks/morpho-sdk`,
    rawHref: `${DOCS}/developers/sdks/morpho-sdk.md`,
    why: "The application integration layer for vaults and markets, including approvals, permits, bundles and native wrapping. Prefer it over hand-built calls.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 4,
  },
  {
    id: "morpho.sdk-architecture",
    family: "morpho",
    title: "SDK architecture notes",
    kind: "docs",
    href: "https://github.com/morpho-org/sdks/blob/main/packages/morpho-sdk/ARCHITECTURE.md",
    rawHref:
      "https://raw.githubusercontent.com/morpho-org/sdks/main/packages/morpho-sdk/ARCHITECTURE.md",
    why: "Worth loading straight into your coding agent. Explains fetchers, entities, transaction builders, bundles and permit flows.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 5,
  },
  {
    id: "morpho.sdk-repo",
    family: "morpho",
    title: "SDK repository",
    kind: "repo",
    href: "https://github.com/morpho-org/sdks",
    why: "The packages, ABIs, constants, simulations and examples behind the SDK docs.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.api",
    family: "morpho",
    title: "Morpho API",
    kind: "docs",
    href: `${DOCS}/developers/api/get-started`,
    rawHref: `${DOCS}/developers/api/get-started.md`,
    why: "Discovery, APYs, TVL, utilization, positions, allocations and rewards without running your own indexer first. Robinhood Chain mainnet is a supported network.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.api-vaults",
    family: "morpho",
    title: "Vault API",
    kind: "docs",
    href: `${DOCS}/developers/api/morpho-vaults`,
    rawHref: `${DOCS}/developers/api/morpho-vaults.md`,
    why: "What your frontend reads to show APY, allocations, history, positions, fees and curator details.",
    shapes: ["embedded_earn"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 6,
  },
  {
    id: "morpho.api-changelog",
    family: "morpho",
    title: "API changelog",
    kind: "docs",
    href: `${DOCS}/developers/api/changelog`,
    rawHref: `${DOCS}/developers/api/changelog.md`,
    why: "Fields get removed. Watch this in CI so a deprecation does not surprise your users.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["reality"],
    priority: "recommended",
  },

  // -- curated vaults ---------------------------------------------------------
  {
    id: "morpho.vault-v2-concepts",
    family: "morpho",
    title: "What a Vault V2 is",
    kind: "docs",
    href: `${DOCS}/learn/concepts/vault-v2`,
    rawHref: `${DOCS}/learn/concepts/vault-v2.md`,
    why: "Adapters, allocation ids, caps and separate curator and allocator roles rather than a plain pool wrapper.",
    shapes: CURATOR_SIDE,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 3,
  },
  {
    id: "morpho.vault-v2-repo",
    family: "morpho",
    title: "Vault V2 repository",
    kind: "repo",
    href: "https://github.com/morpho-org/vault-v2",
    why: "The contracts, tests and specification behind the curated-vault architecture.",
    shapes: CURATOR_SIDE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 7,
  },
  {
    id: "morpho.vault-v2-create",
    family: "morpho",
    title: "Create a Vault V2",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-v2/vault-creation`,
    rawHref: `${DOCS}/curate/tutorials-v2/vault-creation.md`,
    why: "Factory deployment, permanent settings, adapter configuration and hardening. This is the tutorial that replaces a back office.",
    shapes: CURATOR_SIDE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 8,
  },
  {
    id: "morpho.vault-v2-checklist",
    family: "morpho",
    title: "Vault V2 configuration checklist",
    kind: "checklist",
    href: `${DOCS}/curate/tutorials-v2/checklist`,
    rawHref: `${DOCS}/curate/tutorials-v2/checklist.md`,
    why: "Registry locking, gates, adapter hardening, roles, caps, liquidity adapters, dead deposits, timelocks and monitoring bots. Treat it as your deployment gate.",
    shapes: CURATOR_SIDE,
    steps: ["security", "reality", "review"],
    priority: "core",
    readOrder: 9,
  },
  {
    id: "morpho.vault-v2-roles",
    family: "morpho",
    title: "Vault roles",
    kind: "docs",
    href: `${DOCS}/curate/concepts/roles`,
    rawHref: `${DOCS}/curate/concepts/roles.md`,
    why: "Owner, curator, allocator and sentinel are separated on purpose. Design your permission model around that split.",
    shapes: CURATOR_SIDE,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 10,
  },
  {
    id: "morpho.vault-v2-adapters",
    family: "morpho",
    title: "Listing adapters and caps",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-v2/listing-adapters`,
    rawHref: `${DOCS}/curate/tutorials-v2/listing-adapters.md`,
    why: "How exposure caps are expressed for adapters, collateral and individual markets.",
    shapes: CURATOR_SIDE,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.vault-v2-security",
    family: "morpho",
    title: "Vault security considerations",
    kind: "docs",
    href: `${DOCS}/curate/concepts/security-considerations`,
    rawHref: `${DOCS}/curate/concepts/security-considerations.md`,
    why: "What can go wrong for a curator and the mechanisms that limit it.",
    shapes: CURATOR_SIDE,
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "morpho.public-allocator",
    family: "morpho",
    title: "Public allocator",
    kind: "docs",
    href: `${DOCS}/learn/concepts/public-allocator`,
    rawHref: `${DOCS}/learn/concepts/public-allocator.md`,
    why: "Lets eligible vault liquidity move between markets on demand without changing the curator's caps. A borrowing interface can expose more usable liquidity with it.",
    shapes: ["curated_vault", ...VAULT_SHAPES, "collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 11,
  },
  {
    id: "morpho.public-allocator-tutorial",
    family: "morpho",
    title: "Public allocator for borrow flows",
    kind: "docs",
    href: `${DOCS}/developers/borrow/tutorials/public-allocator`,
    rawHref: `${DOCS}/developers/borrow/tutorials/public-allocator.md`,
    why: "Build a reallocation snapshot and attach it to a borrow action so one market can draw on shared liquidity.",
    shapes: [...BORROW_SIDE, "liquidity_allocator"],
    steps: ["architecture"],
    priority: "recommended",
  },

  // -- vault operations shared with the Liquidity sector (M34) -----------------
  {
    id: "morpho.blue-concepts",
    family: "morpho",
    title: "Variable-rate market concepts",
    kind: "docs",
    href: `${DOCS}/learn/concepts/blue`,
    rawHref: `${DOCS}/learn/concepts/blue.md`,
    why: "One collateral, one loan asset, one oracle, one rate model and one liquidation threshold, fixed at creation. The market tuple every vault allocates into and every allocator routes between.",
    shapes: [...BORROW_SIDE, ...CURATOR_SIDE],
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.vault-v2-dead-deposit",
    family: "morpho",
    title: "Vault V2 dead deposit",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-v2/dead-deposit`,
    rawHref: `${DOCS}/curate/tutorials-v2/dead-deposit.md`,
    why: "The first deposit into an empty vault, sent to a burn address, so nobody can inflate the share price against your first real depositor. Do it before the vault is announced.",
    shapes: CURATOR_SIDE,
    steps: ["security", "reality"],
    priority: "core",
    readOrder: 12,
  },
  {
    id: "morpho.vault-v2-roles-tutorial",
    family: "morpho",
    title: "Configure Vault V2 roles",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-v2/roles`,
    rawHref: `${DOCS}/curate/tutorials-v2/roles.md`,
    why: "The calls that hand owner, curator, allocator and sentinel to their keys, with the separation of powers the concepts page argues for. Pair it with the role model in the kit.",
    shapes: CURATOR_SIDE,
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "morpho.vault-gates",
    family: "morpho",
    title: "Vault gates",
    kind: "docs",
    href: `${DOCS}/curate/concepts/gates`,
    rawHref: `${DOCS}/curate/concepts/gates.md`,
    why: "Who may deposit, withdraw, receive and send shares, enforced by the vault. The contract half of a permissioned product; the allowlist and the exit rights are still yours to write.",
    shapes: CURATOR_SIDE,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 13,
  },
  {
    id: "morpho.vault-v2-emergency",
    family: "morpho",
    title: "Vault V2 emergency procedures",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-v2/emergency`,
    rawHref: `${DOCS}/curate/tutorials-v2/emergency.md`,
    why: "Deprecating a market softly or hard, a compromised role, an adapter that stops returning assets. Rehearse each one on a fork before there is a depositor to protect.",
    shapes: CURATOR_SIDE,
    steps: ["security", "reality"],
    priority: "recommended",
  },
  {
    id: "morpho.vault-v2-unwind",
    family: "morpho",
    title: "Unwind a Vault V2",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-v2/unwind-vault-v2`,
    rawHref: `${DOCS}/curate/tutorials-v2/unwind-vault-v2.md`,
    why: "Block deposits, pull exposure back to idle, let everyone leave. A product that cannot be wound down cleanly is a product that traps its depositors.",
    shapes: CURATOR_SIDE,
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "morpho.permissioned-assets",
    family: "morpho",
    title: "Permissioned tokens in markets and vaults",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-market-v1/permissioned-assets`,
    rawHref: `${DOCS}/curate/tutorials-market-v1/permissioned-assets.md`,
    why: "Which protocol contracts a token issuer must allowlist so a transfer-restricted asset can be supplied, borrowed, bundled and liquidated. Tokenised securities fail here first.",
    shapes: ["permissioned_vault", "curated_vault", "collateral_loans"],
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 14,
  },
  {
    id: "morpho.bundles",
    family: "morpho",
    title: "Bundles",
    kind: "docs",
    href: `${DOCS}/learn/concepts/bundles`,
    rawHref: `${DOCS}/learn/concepts/bundles.md`,
    why: "Several protocol calls in one transaction through an intermediate contract. That contract briefly holds the assets, which matters the moment one of them is transfer-restricted.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.liquidation-concept",
    family: "morpho",
    title: "Liquidation, the lender's view",
    kind: "docs",
    href: `${DOCS}/learn/concepts/liquidation`,
    rawHref: `${DOCS}/learn/concepts/liquidation.md`,
    why: "The threshold, the incentive and the bad-debt path explained for whoever supplies the market. A vault or an allocator is only as safe as the liquidations of the markets it funds.",
    shapes: [...BORROW_SIDE, ...CURATOR_SIDE],
    steps: ["security"],
    priority: "recommended",
  },

  // -- CanHav liquidity kit files for the vault shapes (M36) --------------------
  {
    id: "canhav.vault-specification",
    family: "morpho",
    title: "Vault specification",
    kind: "template",
    href: `${LIQUIDITY_KIT}/VAULT_SPECIFICATION.md`,
    rawHref: `${LIQUIDITY_KIT}/VAULT_SPECIFICATION.md`,
    why: "One file per vault. Asset, roles and their keys, gates, adapters and caps, timelocks, fee, cash buffer and redemption terms, filled in before the factory is called.",
    shapes: CURATOR_SIDE,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 28,
  },
  {
    id: "canhav.liquidity-scenarios",
    family: "morpho",
    title: "Liquidity scenarios",
    kind: "template",
    href: `${LIQUIDITY_KIT}/LIQUIDITY_SCENARIOS.md`,
    rawHref: `${LIQUIDITY_KIT}/LIQUIDITY_SCENARIOS.md`,
    why: "The six scenarios a lender-facing vault has to survive, weekend gap, oracle pause, sequencer outage, thin collateral market, lender run and depeg, each with the test to run, the control to have and the numbers to keep.",
    shapes: [...CURATOR_SIDE, "embedded_earn", "collateral_loans"],
    steps: ["security", "reality"],
    priority: "core",
    readOrder: 29,
  },
  {
    id: "canhav.release-gates",
    family: "morpho",
    title: "Release gates",
    kind: "template",
    href: `${LIQUIDITY_KIT}/RELEASE_GATES.md`,
    rawHref: `${LIQUIDITY_KIT}/RELEASE_GATES.md`,
    why: "Seven phases from product definition to scale, each with the evidence that lets it pass, and the team documents a small team keeps so a reviewer can follow the trail.",
    shapes: [...CURATOR_SIDE, "embedded_earn", "collateral_loans"],
    steps: ["reality", "review"],
    priority: "recommended",
  },
  {
    id: "canhav.gates-and-eligibility",
    family: "morpho",
    title: "Gates and eligibility",
    kind: "template",
    href: `${LIQUIDITY_KIT}/GATES_AND_ELIGIBILITY.md`,
    rawHref: `${LIQUIDITY_KIT}/GATES_AND_ELIGIBILITY.md`,
    why: "The allowlist design for a permissioned vault. Who may deposit, borrow and hold shares, which jurisdictions, who the custodian is, where the institutional price comes from and what exit rights a gate can never override.",
    shapes: ["permissioned_vault"],
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 30,
  },

  // -- earn inside an app ----------------------------------------------------
  {
    id: "morpho.earn-get-started",
    family: "morpho",
    title: "Earn integration overview",
    kind: "docs",
    href: `${DOCS}/developers/earn/get-started`,
    rawHref: `${DOCS}/developers/earn/get-started.md`,
    why: "The whole application shape for an earn feature, from vault operations to positions, rewards and the risk information users must see.",
    shapes: ["embedded_earn"],
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 3,
  },
  {
    id: "morpho.vault-mechanics",
    family: "morpho",
    title: "Vaults and ERC-4626 mechanics",
    kind: "docs",
    href: `${DOCS}/developers/earn/concepts/vault-mechanics`,
    rawHref: `${DOCS}/developers/earn/concepts/vault-mechanics.md`,
    why: "Deposits, shares, redemptions and the places where a Vault V2 departs from the standard, such as maxDeposit and maxWithdraw.",
    shapes: VAULT_SIDE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 7,
  },
  {
    id: "morpho.earn-rewards",
    family: "morpho",
    title: "Rewards for earn products",
    kind: "docs",
    href: `${DOCS}/developers/earn/tutorials/rewards`,
    rawHref: `${DOCS}/developers/earn/tutorials/rewards.md`,
    why: "Show native yield, incentive campaigns and fees as separate numbers. One opaque figure is the thing reviewers reject first.",
    shapes: ["embedded_earn"],
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "morpho.earn-ux",
    family: "morpho",
    title: "Earn UX requirements",
    kind: "checklist",
    href: `${DOCS}/developers/earn/vault-ux/ux-requirement`,
    rawHref: `${DOCS}/developers/earn/vault-ux/ux-requirement.md`,
    why: "What an earn surface must disclose and how rates are presented. Read before designing a single screen.",
    shapes: ["embedded_earn"],
    steps: ["security", "review"],
    priority: "recommended",
  },
  {
    id: "morpho.earn-revenue",
    family: "morpho",
    title: "How distributors earn revenue",
    kind: "docs",
    href: `${DOCS}/developers/earn/concepts/generate-revenue`,
    rawHref: `${DOCS}/developers/earn/concepts/generate-revenue.md`,
    why: "The fee wrapper and the business model for an app that routes deposits it does not underwrite.",
    shapes: ["embedded_earn"],
    steps: ["basics", "reality"],
    priority: "recommended",
  },
  {
    id: "morpho.snippets",
    family: "morpho",
    title: "Solidity snippets",
    kind: "repo",
    href: "https://github.com/morpho-org/morpho-blue-snippets",
    why: "Reference implementations of on-chain reads and interactions when you need more than the SDK abstraction.",
    shapes: LENDING_AND_VAULTS,
    steps: ["architecture"],
    priority: "recommended",
  },

  // -- collateral-backed loans -------------------------------------------------
  {
    id: "morpho.borrow-get-started",
    family: "morpho",
    title: "Borrow integration overview",
    kind: "docs",
    href: `${DOCS}/developers/borrow/get-started`,
    rawHref: `${DOCS}/developers/borrow/get-started.md`,
    why: "Defines the three surfaces you own, market operations, position health and rewards. Start here.",
    shapes: BORROW_SIDE,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 3,
  },
  {
    id: "morpho.borrow-assets-flow",
    family: "morpho",
    title: "Supply collateral, borrow, repay, withdraw",
    kind: "docs",
    href: `${DOCS}/developers/borrow/tutorials/assets-flow`,
    rawHref: `${DOCS}/developers/borrow/tutorials/assets-flow.md`,
    why: "The first implementation tutorial for a borrowing MVP, using the SDK rather than hand-composed calls.",
    shapes: BORROW_SIDE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 6,
  },
  {
    id: "morpho.blue-repo",
    family: "morpho",
    title: "Morpho Blue repository",
    kind: "repo",
    href: "https://github.com/morpho-org/morpho-blue",
    why: "The core protocol, its audits, tests and whitepaper in one place.",
    shapes: BORROW_SIDE,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 7,
  },
  {
    id: "morpho.blue-whitepaper",
    family: "morpho",
    title: "Morpho Blue whitepaper",
    kind: "paper",
    href: "https://github.com/morpho-org/morpho-blue/blob/main/morpho-blue-whitepaper.pdf",
    why: "Isolated markets, market construction, rate mechanics and liquidation, with the reasoning behind each choice.",
    shapes: [...BORROW_SIDE, ...CURATOR_SIDE],
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.market-mechanics",
    family: "morpho",
    title: "Market mechanics",
    kind: "docs",
    href: `${DOCS}/developers/borrow/concepts/market-mechanics`,
    rawHref: `${DOCS}/developers/borrow/concepts/market-mechanics.md`,
    why: "Assets and shares accounting, and why debt balances and positions are not simple token balances.",
    shapes: BORROW_SIDE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 8,
  },
  {
    id: "morpho.ltv-health",
    family: "morpho",
    title: "Collateral, LTV and health",
    kind: "docs",
    href: `${DOCS}/developers/borrow/concepts/ltv`,
    rawHref: `${DOCS}/developers/borrow/concepts/ltv.md`,
    why: "LTV, the immutable liquidation threshold and the health-factor arithmetic. This is a frontend requirement, not just backend knowledge.",
    shapes: BORROW_SIDE,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 9,
  },
  {
    id: "morpho.liquidation",
    family: "morpho",
    title: "Liquidation",
    kind: "docs",
    href: `${DOCS}/developers/borrow/concepts/liquidation`,
    rawHref: `${DOCS}/developers/borrow/concepts/liquidation.md`,
    why: "How positions are closed out and what your users need to see before it happens to them.",
    shapes: BORROW_SIDE,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 10,
  },
  {
    id: "morpho.interest-rates",
    family: "morpho",
    title: "Interest rates",
    kind: "docs",
    href: `${DOCS}/developers/borrow/concepts/interest-rates`,
    rawHref: `${DOCS}/developers/borrow/concepts/interest-rates.md`,
    why: "How the adaptive rate model moves with utilization, which decides the borrow leg of any spread you advertise.",
    shapes: [...BORROW_SIDE, "liquidity_allocator"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.oracle-concept",
    family: "morpho",
    title: "Oracles in a market",
    kind: "docs",
    href: `${DOCS}/learn/concepts/oracle`,
    rawHref: `${DOCS}/learn/concepts/oracle.md`,
    why: "A market's oracle is one of its immutable parameters. Getting it wrong cannot be patched later.",
    shapes: [...BORROW_SIDE, "permissioned_vault"],
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 11,
  },
  {
    id: "morpho.oracle-deploy",
    family: "morpho",
    title: "Deploy an oracle for a market",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-market-v1/deploying-oracle`,
    rawHref: `${DOCS}/curate/tutorials-market-v1/deploying-oracle.md`,
    why: "The factory path for a feed-based oracle, and the parameter choices it forces you to make explicitly.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.oracle-contracts",
    family: "morpho",
    title: "Oracle contracts",
    kind: "docs",
    href: `${DOCS}/developers/contracts/oracles`,
    rawHref: `${DOCS}/developers/contracts/oracles.md`,
    why: "The oracle interface and the reference implementations, for when you wrap a feed that is not already supported.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "morpho.create-market",
    family: "morpho",
    title: "Create a market",
    kind: "docs",
    href: `${DOCS}/curate/tutorials-market-v1/creating-market`,
    rawHref: `${DOCS}/curate/tutorials-market-v1/creating-market.md`,
    why: "Collateral, loan asset, oracle, rate model and liquidation threshold are fixed at creation. This walks the call.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 12,
  },
  {
    id: "morpho.monetize-borrow",
    family: "morpho",
    title: "Monetizing a borrow product",
    kind: "docs",
    href: `${DOCS}/developers/borrow/guides/monetize-borrow-product`,
    rawHref: `${DOCS}/developers/borrow/guides/monetize-borrow-product.md`,
    why: "Documents an integration-layer origination fee. The example contracts are educational and unaudited, but the business model is real.",
    shapes: BORROW_SIDE,
    steps: ["basics", "reality"],
    priority: "recommended",
  },

  // -- reference and risk --------------------------------------------------------
  {
    id: "morpho.risks",
    family: "morpho",
    title: "Protocol risks",
    kind: "docs",
    href: `${DOCS}/learn/resources/risks`,
    rawHref: `${DOCS}/learn/resources/risks.md`,
    why: "The protocol's own list of what can go wrong. Your disclosures should not say less than this.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "morpho.audits",
    family: "morpho",
    title: "Audits",
    kind: "docs",
    href: `${DOCS}/get-started/resources/audits/`,
    why: "Every audit report, for the day a reviewer asks which assumptions were already checked.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["security"],
    priority: "deep_dive",
  },
  {
    id: "morpho.whitepapers",
    family: "morpho",
    title: "Research and whitepapers",
    kind: "paper",
    href: `${DOCS}/get-started/resources/whitepapers`,
    rawHref: `${DOCS}/get-started/resources/whitepapers.md`,
    why: "Rate optimization and liquidation research for the day your product needs its own risk scoring rather than someone else's.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "morpho.addresses",
    family: "morpho",
    title: "Official contract addresses",
    kind: "addresses",
    href: `${DOCS}/developers/contracts/addresses`,
    rawHref: `${DOCS}/developers/contracts/addresses.md`,
    why: "The official registry. It lists Robinhood Chain mainnet and, at last check, no testnet deployment.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["reality"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "canhav.asset-research-template",
    family: "morpho",
    title: "Asset research template",
    kind: "template",
    href: `${KIT}/COLLATERAL_ASSET_RESEARCH.md`,
    rawHref: `${KIT}/COLLATERAL_ASSET_RESEARCH.md`,
    why: "One file per asset before it is approved as collateral, loan asset or vault asset. Identity, price, liquidity, risk, proposed parameters, checklist result.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 26,
  },
  {
    id: "canhav.testnet-manifest",
    family: "morpho",
    title: "Testnet 46630 manifest (CanHav copy)",
    chains: ["robinhood_testnet"],
    kind: "addresses",
    href: `${KIT}/robinhood-testnet-46630.manifest.json`,
    rawHref: `${KIT}/robinhood-testnet-46630.manifest.json`,
    why: "The community deployment above as one JSON your config can read, with the unofficial notice first, the enabled thresholds in percent, and nulls where nothing is deployed.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["reality"],
    priority: "recommended",
    flags: ["unofficial", "testnet_only"],
  },
  {
    id: "morpho.testnet-community-deployment",
    family: "morpho",
    title: "Community Morpho Blue deployment on testnet 46630",
    chains: ["robinhood_testnet"],
    kind: "addresses",
    href: "https://github.com/EqualFiLabs/Statics/blob/master/deployments/robinhood-testnet-46630-morpho.json",
    rawHref:
      "https://raw.githubusercontent.com/EqualFiLabs/Statics/master/deployments/robinhood-testnet-46630-morpho.json",
    why: "A verified community deployment of the core market contracts and the adaptive rate model, with pinned commits and the standard liquidation threshold set. Not official infrastructure, useful as a shared test fixture. It deploys no oracle and no market.",
    shapes: [...LENDING_AND_VAULTS, "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["reality"],
    priority: "core",
    readOrder: 20,
    flags: ["unofficial", "testnet_only"],
  },
];
