import { MCP_CONNECT } from "@/content/launch";
import type { KitResource } from "@/lib/kits";

const KIT = `${MCP_CONNECT.baseUrl}/kits/credit/pendle`;
const DOCS = "https://docs.pendle.finance";
const DEV = `${DOCS}/pendle-v2-dev`;
const MECH = `${DOCS}/pendle-v2/ProtocolMechanics`;
const CORE = "https://github.com/pendle-finance/pendle-core-v2-public";
const CORE_RAW = "https://raw.githubusercontent.com/pendle-finance/pendle-core-v2-public/main";
const AI = "https://github.com/pendle-finance/pendle-ai";
const AI_RAW = "https://raw.githubusercontent.com/pendle-finance/pendle-ai/main";
const SKILLS = `${AI}/blob/main/packages/plugins/pendle-v2/skills`;
const SKILLS_RAW = `${AI_RAW}/packages/plugins/pendle-v2/skills`;

/** Every shape that touches a fixed or variable half. */
const ALL_PENDLE = [
  "fixed_rate_yield",
  "embedded_fixed_rate",
  "pt_backed_borrowing",
  "leveraged_fixed_yield",
  "yield_token_exposure",
] as const;
/** Wraps an asset and opens a market. */
const ISSUER = ["fixed_rate_yield"] as const;
/** Buys or sells a half on behalf of users. */
const SWAP = ["embedded_fixed_rate", "leveraged_fixed_yield", "yield_token_exposure"] as const;
/** Values the fixed half as collateral. */
const COLLATERAL = ["pt_backed_borrowing", "leveraged_fixed_yield"] as const;
/** Everyone who holds a half for users. */
const HOLDER = ["embedded_fixed_rate", "pt_backed_borrowing", "leveraged_fixed_yield", "yield_token_exposure"] as const;

/**
 * Pendle family. The hosted API, SDK, MCP and skills serve the chains the
 * protocol is live on, and on Robinhood Chain that is mainnet 4663 only, so
 * they carry mainnet_only. Pendle docs pages do not serve raw markdown; the
 * whole corpus is llms-full.txt. Ids are immutable.
 */
export const PENDLE_RESOURCES: readonly KitResource[] = [
  // -- agent skills and docs for agents --------------------------------------
  {
    id: "pendle.skill-swap",
    family: "pendle",
    title: "Swap skill",
    kind: "skill",
    href: `${SKILLS}/pendle-swap/SKILL.md`,
    rawHref: `${SKILLS_RAW}/pendle-swap/SKILL.md`,
    why: "Instructions for a coding agent that buys or sells the fixed and variable halves and adds or removes liquidity through the hosted SDK.",
    shapes: SWAP,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 1,
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.skill-data",
    family: "pendle",
    title: "Market data skill",
    kind: "skill",
    href: `${SKILLS}/pendle-data/SKILL.md`,
    rawHref: `${SKILLS_RAW}/pendle-data/SKILL.md`,
    why: "How an agent reads markets, implied rates, maturities and liquidity from the hosted API before it proposes a product.",
    shapes: ALL_PENDLE,
    steps: ["basics", "reality"],
    priority: "core",
    readOrder: 2,
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.skill-portfolio",
    family: "pendle",
    title: "Portfolio skill",
    kind: "skill",
    href: `${SKILLS}/pendle-portfolio/SKILL.md`,
    rawHref: `${SKILLS_RAW}/pendle-portfolio/SKILL.md`,
    why: "Reading a user's positions across halves and pools, which is what an embedded product shows on its balance screen.",
    shapes: HOLDER,
    steps: ["architecture"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.skill-order",
    family: "pendle",
    title: "Limit order skill",
    kind: "skill",
    href: `${SKILLS}/pendle-order/SKILL.md`,
    rawHref: `${SKILLS_RAW}/pendle-order/SKILL.md`,
    why: "Placing and cancelling limit orders on a half, useful when a product wants a target rate rather than the pool's price.",
    shapes: SWAP,
    steps: ["architecture"],
    priority: "deep_dive",
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.ai-repo",
    family: "pendle",
    title: "Pendle AI plugins repository",
    kind: "repo",
    href: AI,
    rawHref: `${AI_RAW}/README.md`,
    why: "The marketplace that ships the skills, the advisor agent and both MCP servers, with install lines for Claude Code, Cursor and Codex.",
    shapes: ALL_PENDLE,
    steps: ["basics"],
    priority: "recommended",
  },
  {
    id: "pendle.llms",
    family: "pendle",
    title: "Pendle docs for agents (llms-full.txt)",
    kind: "docs",
    href: `${DOCS}/llms-full.txt`,
    rawHref: `${DOCS}/llms-full.txt`,
    why: "The whole developer corpus for V2 and Boros in one file. Load it before the agent guesses at a contract or an endpoint.",
    shapes: ALL_PENDLE,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 3,
  },
  {
    id: "pendle.mcp",
    family: "pendle",
    title: "Pendle V2 remote MCP server",
    kind: "tool",
    href: `${AI}#pendle-v2-mcp-install`,
    why: "A hosted streamable HTTP server at api-v2.pendle.finance/core/mcp with the market, swap and portfolio tools. No install, one URL, mainnet chains only.",
    shapes: ALL_PENDLE,
    steps: ["basics", "architecture"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.ai-guide",
    family: "pendle",
    title: "Pendle AI app guide",
    kind: "docs",
    href: `${DOCS}/pendle-v2/AppGuide/PendleAI`,
    why: "What the AI tooling can and cannot do today, from the protocol team, so a product does not promise an agent feature that is not there.",
    shapes: ALL_PENDLE,
    steps: ["reality"],
    priority: "deep_dive",
  },

  // -- hosted SDK, API and router ----------------------------------------------
  {
    id: "pendle.hosted-sdk",
    family: "pendle",
    title: "Hosted SDK",
    kind: "docs",
    href: `${DEV}/Backend/HostedSdk`,
    why: "Returns ready calldata for swaps, mints, redemptions and liquidity moves, so your app never assembles router calls by hand.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 4,
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.api",
    family: "pendle",
    title: "Backend API overview",
    kind: "docs",
    href: `${DEV}/Backend/ApiOverview`,
    why: "Markets, prices, implied rates and positions over REST, which is where an embedded product reads the rate it displays.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.openapi",
    family: "pendle",
    title: "V2 OpenAPI specification",
    kind: "spec",
    href: "https://api-v2.pendle.finance/core/docs",
    rawHref: "https://api-v2.pendle.finance/core/docs/json",
    why: "The machine-readable surface of the hosted API. Generate a typed client from it instead of hand-writing fetch calls.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.sdk-repo",
    family: "pendle",
    title: "SDK core repository",
    kind: "repo",
    href: "https://github.com/pendle-finance/pendle-sdk-core-v2-public",
    rawHref: "https://raw.githubusercontent.com/pendle-finance/pendle-sdk-core-v2-public/main/README.md",
    why: "The TypeScript SDK behind the hosted service, for teams that would rather run the routing logic themselves.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "pendle.router",
    family: "pendle",
    title: "Router overview",
    kind: "docs",
    href: `${DEV}/Contracts/PendleRouter/PendleRouterOverview`,
    why: "The one contract a swap product calls. Which actions exist, how slippage guards work and what a route looks like.",
    shapes: SWAP,
    steps: ["architecture"],
    priority: "core",
    readOrder: 5,
  },
  {
    id: "pendle.router-integration",
    family: "pendle",
    title: "Router contract integration guide",
    kind: "docs",
    href: `${DEV}/Contracts/PendleRouter/ContractIntegrationGuide`,
    why: "Calling the router from your own contract rather than from a frontend, which a loop product or a vault adapter must do.",
    shapes: ["leveraged_fixed_yield", "embedded_fixed_rate"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.router-static",
    family: "pendle",
    title: "RouterStatic",
    kind: "docs",
    href: `${DEV}/Backend/RouterStatic`,
    why: "Read-only previews of what a swap or a mint would return, for quotes and for tests.",
    shapes: SWAP,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "pendle.limit-orders",
    family: "pendle",
    title: "Limit order overview",
    kind: "docs",
    href: `${DEV}/LimitOrder/Overview`,
    why: "Off-chain signed orders filled on-chain. Relevant when a product promises users a specific fixed rate instead of the pool's.",
    shapes: SWAP,
    steps: ["architecture"],
    priority: "deep_dive",
  },

  // -- the standard yield wrapper -----------------------------------------------
  {
    id: "pendle.sy-concept",
    family: "pendle",
    title: "What a standardized yield token is",
    kind: "docs",
    href: `${MECH}/YieldTokenization/SY`,
    why: "The wrapper every yield-bearing asset passes through before it can be split. Start here if the phrase exchange rate is new.",
    shapes: ALL_PENDLE,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 6,
  },
  {
    id: "pendle.sy-interface",
    family: "pendle",
    title: "IStandardizedYield.sol",
    kind: "spec",
    href: `${CORE}/blob/main/contracts/interfaces/IStandardizedYield.sol`,
    rawHref: `${CORE_RAW}/contracts/interfaces/IStandardizedYield.sol`,
    why: "The interface your wrapper must implement. Deposit, redeem, exchangeRate and the reward hooks, with the invariants in the comments.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "core",
    readOrder: 7,
  },
  {
    id: "pendle.sy-contracts",
    family: "pendle",
    title: "Standardized yield contract docs",
    kind: "docs",
    href: `${DEV}/Contracts/StandardizedYield`,
    why: "The developer view of the wrapper, from the base contracts to what a new implementation must override.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "core",
    readOrder: 8,
  },
  {
    id: "pendle.common-sy",
    family: "pendle",
    title: "Common SY contracts",
    kind: "docs",
    href: `${DEV}/Contracts/StandardizedYield/CommonSY`,
    why: "Ready wrappers for common cases, including one over an ERC-4626 vault with an adapter. Most teams wrap without writing Solidity.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "core",
    readOrder: 9,
  },
  {
    id: "pendle.sy-public",
    family: "pendle",
    title: "Pendle-SY-Public repository",
    kind: "repo",
    href: "https://github.com/pendle-finance/Pendle-SY-Public",
    rawHref: "https://raw.githubusercontent.com/pendle-finance/Pendle-SY-Public/main/README.md",
    why: "Every wrapper the protocol has shipped, as source. Copy the closest one rather than starting from the interface.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.sy-tests",
    family: "pendle",
    title: "SY test suite",
    kind: "repo",
    href: "https://github.com/pendle-finance/pendle-sy-tests",
    rawHref: "https://raw.githubusercontent.com/pendle-finance/pendle-sy-tests/main/README.md",
    why: "The conformance tests a wrapper must pass before a market is opened on it. Run them in CI from day one.",
    shapes: ISSUER,
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "pendle.decimals-wrapper",
    family: "pendle",
    title: "Decimals wrapper",
    kind: "docs",
    href: `${DEV}/Contracts/StandardizedYield/DecimalsWrapper`,
    why: "Assets with few decimals lose precision inside the math. This wrapper fixes it, and it is easy to forget for a six-decimal stablecoin.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "deep_dive",
  },

  // -- the two halves ------------------------------------------------------------
  {
    id: "pendle.pt-concept",
    family: "pendle",
    title: "What the fixed half is",
    kind: "docs",
    href: `${MECH}/YieldTokenization/PT`,
    why: "A claim on one unit of the asset at maturity, bought at a discount. The discount is the fixed rate your users see.",
    shapes: ALL_PENDLE,
    steps: ["basics"],
    priority: "core",
    readOrder: 6,
  },
  {
    id: "pendle.yt-concept",
    family: "pendle",
    title: "What the variable half is",
    kind: "docs",
    href: `${MECH}/YieldTokenization/YT`,
    why: "Pays the yield of the asset until maturity and is worth zero after. Everything a leveraged yield product must disclose starts here.",
    shapes: ["yield_token_exposure", "fixed_rate_yield", "leveraged_fixed_yield"],
    steps: ["basics", "security"],
    priority: "core",
    readOrder: 7,
  },
  {
    id: "pendle.minting",
    family: "pendle",
    title: "Minting and redeeming the halves",
    kind: "docs",
    href: `${MECH}/YieldTokenization/Minting`,
    why: "One wrapped unit becomes one fixed and one variable half, and the pair redeems back before maturity. The accounting your product inherits.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.yield-tokenization-contracts",
    family: "pendle",
    title: "Yield tokenization contracts",
    kind: "docs",
    href: `${DEV}/Contracts/YieldTokenization`,
    why: "The factory and the two token contracts, and how the index that ties them to the wrapper is read and updated.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "core",
    readOrder: 10,
  },
  {
    id: "pendle.pt-contract",
    family: "pendle",
    title: "PendlePrincipalToken.sol",
    kind: "spec",
    href: `${CORE}/blob/main/contracts/core/YieldContracts/PendlePrincipalToken.sol`,
    rawHref: `${CORE_RAW}/contracts/core/YieldContracts/PendlePrincipalToken.sol`,
    why: "A plain token with an expiry and a redemption path. Read it before treating the fixed half like any other ERC-20 in a lending market.",
    shapes: COLLATERAL,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "pendle.yt-contract",
    family: "pendle",
    title: "PendleYieldToken.sol",
    kind: "spec",
    href: `${CORE}/blob/main/contracts/core/YieldContracts/PendleYieldToken.sol`,
    rawHref: `${CORE_RAW}/contracts/core/YieldContracts/PendleYieldToken.sol`,
    why: "Where interest and rewards accrue to the variable half and how they are claimed. The decay is in the math here.",
    shapes: ["yield_token_exposure"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.py-index",
    family: "pendle",
    title: "PYIndex.sol",
    kind: "spec",
    href: `${CORE}/blob/main/contracts/core/StandardizedYield/PYIndex.sol`,
    rawHref: `${CORE_RAW}/contracts/core/StandardizedYield/PYIndex.sol`,
    why: "The index that converts between wrapped units and halves. A cross-protocol invariant checks it against the wrapper's exchange rate.",
    shapes: ["fixed_rate_yield", "yield_token_exposure"],
    steps: ["security"],
    priority: "deep_dive",
  },

  // -- the market ----------------------------------------------------------------
  {
    id: "pendle.market-contracts",
    family: "pendle",
    title: "Market contract docs",
    kind: "docs",
    href: `${DEV}/Contracts/PendleMarket`,
    why: "The pool that trades the fixed half against wrapped units with time in the curve. What the parameters mean and what expiry does to it.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "core",
    readOrder: 11,
  },
  {
    id: "pendle.common-market-deployments",
    family: "pendle",
    title: "Common market deployments",
    kind: "docs",
    href: `${DEV}/Contracts/PendleMarket/CommonMarketDeployments`,
    why: "The deploy helper and its inputs, expiry, the rate band, the initial implied rate and the fee. These are product decisions, not just parameters.",
    shapes: ISSUER,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 12,
  },
  {
    id: "pendle.amm-concept",
    family: "pendle",
    title: "How the time-aware pool prices a half",
    kind: "docs",
    href: `${MECH}/LiquidityEngines/AMM`,
    why: "Why the curve tightens as maturity approaches and what that means for slippage, liquidity and the rate your users get.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.amm-whitepaper",
    family: "pendle",
    title: "V2 AMM whitepaper",
    kind: "paper",
    href: "https://github.com/pendle-finance/pendle-v2-resources/blob/main/whitepapers/V2_AMM.pdf",
    why: "The full derivation of the curve. Read it before changing a rate band or seeding a pool with real money.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.market-v7",
    family: "pendle",
    title: "PendleMarketV7.sol",
    kind: "spec",
    href: `${CORE}/blob/main/contracts/core/Market/PendleMarketV7.sol`,
    rawHref: `${CORE_RAW}/contracts/core/Market/PendleMarketV7.sol`,
    why: "The current market implementation. Swap, mint and burn entry points and the observation ring used by the oracles.",
    shapes: ISSUER,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "pendle.fees",
    family: "pendle",
    title: "Protocol fees",
    kind: "docs",
    href: `${MECH}/Mechanisms/Fees`,
    why: "Swap fees and the protocol's share of yield. The spread arithmetic of a loop and the net rate of a savings product start after these.",
    shapes: ALL_PENDLE,
    steps: ["basics", "reality"],
    priority: "recommended",
  },
  {
    id: "pendle.glossary",
    family: "pendle",
    title: "Glossary",
    kind: "docs",
    href: `${MECH}/Glossary`,
    why: "Implied rate, underlying rate, long yield rate and the rest. Your rate labels should map onto these one to one.",
    shapes: ALL_PENDLE,
    steps: ["basics"],
    priority: "deep_dive",
  },

  // -- the fixed half as collateral ----------------------------------------------
  {
    id: "pendle.oracle-overview",
    family: "pendle",
    title: "Oracle overview",
    kind: "docs",
    href: `${DEV}/Oracles/OracleOverview`,
    why: "The pool-based and the deterministic feeds side by side, and which one the protocol recommends for lending.",
    shapes: COLLATERAL,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 6,
  },
  {
    id: "pendle.pt-as-collateral",
    family: "pendle",
    title: "The fixed half as collateral in a money market",
    kind: "docs",
    href: `${DEV}/Oracles/PTAsCollateral`,
    why: "The protocol's own guide to listing the fixed half, with the spread example that motivates the loop. Curators on Morpho follow it.",
    shapes: COLLATERAL,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 7,
  },
  {
    id: "pendle.linear-discount-oracle",
    family: "pendle",
    title: "Linear discount oracle",
    kind: "docs",
    href: `${DEV}/Oracles/DeterministicOracles/LinearDiscountOracle`,
    why: "A deterministic price that starts below par and reaches par at maturity. Nothing to manipulate, and no dependence on pool depth.",
    shapes: COLLATERAL,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 8,
  },
  {
    id: "pendle.linear-discount-params",
    family: "pendle",
    title: "Choosing linear discount parameters",
    kind: "docs",
    href: `${DEV}/Oracles/DeterministicOracles/ChoosingLinearDiscountParams`,
    why: "How to pick the discount rate so the feed sits under the market price in normal times and the liquidation line still holds.",
    shapes: COLLATERAL,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 9,
  },
  {
    id: "pendle.oracle-integration",
    family: "pendle",
    title: "Integrating the fixed-half and LP oracles",
    kind: "docs",
    href: `${DEV}/Oracles/HowToIntegratePtAndLpOracle`,
    why: "The wrapper that gives the deterministic feed a fresh timestamp, because many lending markets reject a feed that reports none.",
    shapes: COLLATERAL,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 10,
  },
  {
    id: "pendle.oracle-contracts",
    family: "pendle",
    title: "Oracle contracts",
    kind: "repo",
    href: `${CORE}/tree/main/contracts/oracles`,
    why: "Source for the pool-based oracle, the deterministic ones and the feed-shaped wrappers. Deploy from here, do not fork.",
    shapes: COLLATERAL,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.lp-oracle-doc",
    family: "pendle",
    title: "LP oracle note",
    kind: "paper",
    href: "https://github.com/pendle-finance/pendle-v2-resources/blob/main/docs/LP_Oracle_Doc.pdf",
    why: "How a pool position is valued, for the day a product wants to accept LP tokens rather than the fixed half.",
    shapes: COLLATERAL,
    steps: ["architecture"],
    priority: "deep_dive",
  },

  // -- CanHav kit files ------------------------------------------------------------
  {
    id: "canhav.sy-wrapper-checklist",
    family: "pendle",
    title: "Wrapper checklist",
    kind: "checklist",
    href: `${KIT}/SY_WRAPPER_CHECKLIST.md`,
    rawHref: `${KIT}/SY_WRAPPER_CHECKLIST.md`,
    why: "Run before a market is opened on any wrapper. Choice of wrapper, the exchange rate, conformance, roles, readiness, each line ending in evidence.",
    shapes: ISSUER,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 13,
  },
  {
    id: "canhav.market-parameters",
    family: "pendle",
    title: "Market parameter worksheet",
    kind: "template",
    href: `${KIT}/MARKET_PARAMETERS.md`,
    rawHref: `${KIT}/MARKET_PARAMETERS.md`,
    why: "Expiry, rate band, initial implied rate, fee and seed liquidity as product decisions, one copy per market, with the rollover plan.",
    shapes: ISSUER,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 14,
  },
  {
    id: "canhav.pt-collateral-parameters",
    family: "pendle",
    title: "Fixed half as collateral, parameter template",
    kind: "template",
    href: `${KIT}/PT_COLLATERAL_PARAMETERS.md`,
    rawHref: `${KIT}/PT_COLLATERAL_PARAMETERS.md`,
    why: "Feed, discount rate, timestamp wrapper, threshold, term, caps, exit depth and the four scenarios to write down before listing the fixed half.",
    shapes: COLLATERAL,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 11,
  },
  {
    id: "canhav.pendle-mainnet-manifest",
    family: "pendle",
    title: "Mainnet 4663 manifest (CanHav copy)",
    chains: ["robinhood_testnet"],
    kind: "addresses",
    href: `${KIT}/robinhood-mainnet-4663.manifest.json`,
    rawHref: `${KIT}/robinhood-mainnet-4663.manifest.json`,
    why: "The protocol's mainnet addresses as one JSON your config can read, with the unverified-on-testnet flag on the second line, explorer links, and a note that testnet has nothing.",
    shapes: ALL_PENDLE,
    steps: ["reality"],
    priority: "recommended",
    flags: ["mainnet_only", "unofficial"],
  },

  // -- deployments, security, code -------------------------------------------------
  {
    id: "pendle.robinhood-manifest",
    family: "pendle",
    title: "Robinhood Chain mainnet 4663 deployment manifest",
    chains: ["robinhood_testnet"],
    kind: "addresses",
    href: `${CORE}/blob/main/deployments/4663-core.json`,
    rawHref: `${CORE_RAW}/deployments/4663-core.json`,
    why: "Router, factories, wrapper factory, deploy helper and oracle addresses on mainnet, from the protocol's own repository. No testnet 46630 deployment exists.",
    shapes: ALL_PENDLE,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 20,
    flags: ["mainnet_only"],
  },
  {
    id: "pendle.deployments",
    family: "pendle",
    title: "Deployments page",
    kind: "docs",
    href: `${DEV}/Deployments`,
    why: "The human index of every chain manifest. Confirm a chain is listed before you plan a launch on it.",
    shapes: ALL_PENDLE,
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "pendle.core-repo",
    family: "pendle",
    title: "Core V2 repository",
    kind: "repo",
    href: CORE,
    rawHref: `${CORE_RAW}/README.md`,
    why: "The contracts your product depends on, with the deployment manifests and the audits in the same tree.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.examples",
    family: "pendle",
    title: "Examples repository",
    kind: "repo",
    href: "https://github.com/pendle-finance/pendle-examples-public",
    rawHref: "https://raw.githubusercontent.com/pendle-finance/pendle-examples-public/main/README.md",
    why: "Working backend and hosted SDK examples. Faster than reading interfaces when you want the first swap to run today.",
    shapes: ALL_PENDLE,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "pendle.security",
    family: "pendle",
    title: "Security and audits",
    kind: "docs",
    href: `${DOCS}/pendle-v2/Security`,
    why: "Audit history and the bug bounty. Cite it in your own security declarations rather than claiming the protocol is audited in the abstract.",
    shapes: ALL_PENDLE,
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "pendle.audits",
    family: "pendle",
    title: "Audit reports",
    kind: "repo",
    href: `${CORE}/tree/main/audits`,
    why: "The reports themselves. Read the findings that touch the wrapper and the oracle you plan to use.",
    shapes: ALL_PENDLE,
    steps: ["security"],
    priority: "deep_dive",
  },
  {
    id: "pendle.docs-repo",
    family: "pendle",
    title: "Documentation repository",
    kind: "repo",
    href: "https://github.com/pendle-finance/documentation",
    rawHref: "https://raw.githubusercontent.com/pendle-finance/documentation/master/README.md",
    why: "The source of the docs and of llms-full.txt, with the note on how the AI assets are regenerated. Useful when a page and the corpus disagree.",
    shapes: ALL_PENDLE,
    steps: ["basics"],
    priority: "deep_dive",
  },
];
