import type { KitResource } from "@/lib/kits";

const DOCS = "https://docs.robinhood.com/chain";

const COLLATERAL_SHAPES = [
  "collateral_loans",
  "pt_backed_borrowing",
  "leveraged_fixed_yield",
  "curated_vault",
  "fixed_rate_yield",
] as const;

/**
 * Robinhood Chain family. Chain primitives that every protocol layer
 * consumes, so they appear exactly once. Page slugs are checked against the
 * docs site's route table, because the site answers 200 to any path. Ids
 * are immutable.
 */
export const ROBINHOOD_RESOURCES: readonly KitResource[] = [
  {
    id: "robinhood.chain-docs",
    family: "robinhood",
    title: "Robinhood Chain developer docs",
    kind: "docs",
    href: `${DOCS}/`,
    why: "Read first. Architecture, EVM compatibility, sequencing, account abstraction and the intended real-world asset use.",
    shapes: "all",
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 21,
  },
  {
    id: "robinhood.differences-from-ethereum",
    family: "robinhood",
    title: "Differences from Ethereum",
    kind: "docs",
    href: `${DOCS}/differences-from-ethereum`,
    why: "Block numbers, randomness, coinbase, gas and cross-layer sender behaviour all differ. Mandatory before writing a contract.",
    shapes: "all",
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "robinhood.deploy-smart-contracts",
    family: "robinhood",
    title: "Deploy smart contracts",
    kind: "docs",
    href: `${DOCS}/deploy-smart-contracts`,
    why: "Foundry and Hardhat setup and the recommendation to test on testnet 46630 before mainnet.",
    shapes: "all",
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "robinhood.oracles-and-price-feeds",
    family: "robinhood",
    title: "Oracles and price feeds",
    kind: "docs",
    href: `${DOCS}/oracles-and-price-feeds`,
    why: "Which feeds exist on the chain and the staleness and sequencer checks the chain team asks lending systems to make.",
    shapes: "all",
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "robinhood.transaction-finality",
    family: "robinhood",
    title: "Transaction finality",
    kind: "docs",
    href: `${DOCS}/transaction-finality`,
    why: "Sequencer confirmation, posting to Ethereum and Ethereum finality are separate stages. Deposits and collateral moves should know which one they trust.",
    shapes: "all",
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "robinhood.testnet-explorer",
    family: "robinhood",
    title: "Testnet 46630 explorer, RPC and faucet",
    kind: "addresses",
    href: "https://explorer.testnet.chain.robinhood.com",
    why: "The public testnet endpoints. RPC at rpc.testnet.chain.robinhood.com, faucet at faucet.testnet.chain.robinhood.com. Public RPCs are rate limited.",
    shapes: "all",
    steps: ["reality"],
    priority: "core",
    readOrder: 22,
    flags: ["testnet_only"],
  },
  {
    id: "robinhood.connecting",
    family: "robinhood",
    title: "Connecting, RPC and WebSocket endpoints",
    kind: "docs",
    href: `${DOCS}/connecting`,
    why: "Chain ids, public and managed RPC, WebSocket and sequencer endpoints for mainnet 4663 and testnet 46630. Your config file starts here.",
    shapes: "all",
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 22,
  },
  {
    id: "robinhood.mainnet-explorer",
    family: "robinhood",
    title: "Mainnet 4663 explorer",
    kind: "addresses",
    href: "https://robinhoodchain.blockscout.com",
    why: "Contract verification, transaction inspection and ABI retrieval on mainnet, with a Blockscout API behind it for automated verification.",
    shapes: "all",
    steps: ["reality"],
    priority: "core",
    readOrder: 22,
    flags: ["mainnet_only"],
  },
  {
    id: "robinhood.add-network-to-wallet",
    family: "robinhood",
    title: "Add the network to a wallet",
    kind: "docs",
    href: `${DOCS}/add-network-to-wallet`,
    why: "The exact parameters users need. Copy them into your onboarding rather than sending people to find them.",
    shapes: "all",
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "robinhood.gas-and-fees",
    family: "robinhood",
    title: "Gas and fees",
    kind: "docs",
    href: `${DOCS}/gas-and-fees`,
    why: "How the L2 fee and the L1 data fee combine. Liquidations and rebalances are priced in gas, so model it early.",
    shapes: "all",
    steps: ["architecture", "reality"],
    priority: "recommended",
  },
  {
    id: "robinhood.protocol-contracts",
    family: "robinhood",
    title: "Protocol contract registry",
    kind: "addresses",
    href: `${DOCS}/protocol-contracts`,
    why: "The rollup, inbox, bridge, outbox and gateway addresses on both layers, plus the ArbSys precompile. Never hard-code these from memory.",
    shapes: "all",
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "robinhood.bridging",
    family: "robinhood",
    title: "Bridging",
    kind: "docs",
    href: `${DOCS}/bridging`,
    why: "The canonical bridge and the third-party routes. Where user deposits come from and how long a withdrawal takes.",
    shapes: "all",
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "robinhood.cross-chain-messaging",
    family: "robinhood",
    title: "Cross-chain messaging",
    kind: "docs",
    href: `${DOCS}/cross-chain-messaging`,
    why: "L1 to L2 and back, and the general messaging options. Only needed once a product spans chains.",
    shapes: "all",
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "robinhood.stock-tokens",
    family: "robinhood",
    title: "Stock tokens overview",
    kind: "docs",
    href: `${DOCS}/stock-tokens`,
    why: "What the tokenised stocks are, who can hold them and what they are not. Read before proposing one as collateral.",
    shapes: COLLATERAL_SHAPES,
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "robinhood.building-with-stock-tokens",
    family: "robinhood",
    title: "Building with stock tokens",
    kind: "docs",
    href: `${DOCS}/building-with-stock-tokens`,
    why: "Market hours, the display multiplier and transfer rules. Each one is a liquidation edge case for a lending product.",
    shapes: COLLATERAL_SHAPES,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "robinhood.stock-token-apis",
    family: "robinhood",
    title: "Stock token APIs",
    kind: "docs",
    href: `${DOCS}/stock-token-apis`,
    why: "Assets, prices and corporate actions over REST. A split or a dividend changes what a collateral position is worth overnight.",
    shapes: COLLATERAL_SHAPES,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "robinhood.token-contracts",
    family: "robinhood",
    title: "Token contract registry",
    kind: "addresses",
    href: `${DOCS}/contracts`,
    why: "The canonical stock token and asset addresses on mainnet. Resolve symbols through this list, never through a search on the explorer.",
    shapes: COLLATERAL_SHAPES,
    steps: ["architecture"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "robinhood.data-streams",
    family: "robinhood",
    title: "Chainlink Data Streams",
    kind: "docs",
    href: `${DOCS}/data-streams`,
    why: "Low-latency signed prices verified on-chain. The feed shape a liquidation engine for stock tokens should be built around.",
    shapes: COLLATERAL_SHAPES,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "robinhood.account-abstraction",
    family: "robinhood",
    title: "Account abstraction",
    kind: "docs",
    href: `${DOCS}/account-abstraction`,
    why: "Smart accounts and the entry point on the chain. What an agent or an embedded app uses to act for a user without holding keys.",
    shapes: "all",
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "robinhood.run-a-full-node",
    family: "robinhood",
    title: "Run a full node",
    kind: "docs",
    href: `${DOCS}/run-a-full-node`,
    why: "For the day public RPC limits bite. Also the source of the chain config a local fork needs.",
    shapes: "all",
    steps: ["reality"],
    priority: "deep_dive",
  },
  {
    id: "robinhood.notices-and-upgrades",
    family: "robinhood",
    title: "Notices and upgrades",
    kind: "docs",
    href: `${DOCS}/notices-and-upgrades`,
    why: "Scheduled changes to the chain. Subscribe, because an upgrade can change gas or precompile behaviour under a live market.",
    shapes: "all",
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "robinhood.status",
    family: "robinhood",
    title: "Robinhood status page",
    kind: "tool",
    href: "https://status.robinhood.com",
    why: "Incidents and maintenance. Your monitoring should read it, and your liquidation pause should know about sequencer downtime.",
    shapes: "all",
    steps: ["reality"],
    priority: "recommended",
  },
  {
    id: "robinhood.governance",
    family: "robinhood",
    title: "Chain governance",
    kind: "docs",
    href: `${DOCS}/governance`,
    why: "Who can change the chain and how. Part of the trust story you publish for anything that holds value here.",
    shapes: "all",
    steps: ["security"],
    priority: "deep_dive",
  },
];
