import { MCP_CONNECT } from "@/content/launch";
import type { KitResource } from "@/lib/kits";

const KIT = `${MCP_CONNECT.baseUrl}/kits/credit`;
const LIQUIDITY_KIT = `${MCP_CONNECT.baseUrl}/kits/liquidity`;

/** The two liquidity vault shapes (M34). */
const VAULT_SHAPES = ["liquidity_allocator", "permissioned_vault"] as const;
const VAULT_LIKE = ["curated_vault", "embedded_earn", "fixed_rate_yield", "embedded_fixed_rate", ...VAULT_SHAPES] as const;
const LENDING_LIKE = ["collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield"] as const;
/** Every credit shape plus the two vault shapes. Not the pools. */
const CREDIT_AND_VAULTS = [
  "curated_vault",
  "embedded_earn",
  "collateral_loans",
  "fixed_rate_yield",
  "embedded_fixed_rate",
  "pt_backed_borrowing",
  "leveraged_fixed_yield",
  "yield_token_exposure",
  "liquidity_allocator",
  "permissioned_vault",
] as const;
const APP_FLOWS = [
  "embedded_earn",
  "collateral_loans",
  "embedded_fixed_rate",
  "pt_backed_borrowing",
  "leveraged_fixed_yield",
] as const;

/**
 * Shared family. Standards, security tooling, oracle and risk methodology
 * that sit above every protocol. Ids are immutable.
 */
export const SHARED_RESOURCES: readonly KitResource[] = [
  // -- CanHav kit files -----------------------------------------------------------
  {
    id: "canhav.kit-readme",
    family: "shared",
    title: "CanHav credit kit",
    kind: "template",
    href: `${KIT}/README.md`,
    rawHref: `${KIT}/README.md`,
    why: "What is in the kit and how to use it with a coding agent, in one page.",
    shapes: "all",
    kits: ["credit"],
    steps: ["basics"],
    priority: "core",
    readOrder: 0,
  },
  {
    id: "canhav.kit-skill",
    family: "shared",
    title: "Credit kit agent skill",
    kind: "skill",
    href: `${KIT}/SKILL.md`,
    rawHref: `${KIT}/SKILL.md`,
    why: "Install this so your agent loads the pack first, works in order, and never sends a transaction from intent straight to broadcast.",
    shapes: "all",
    kits: ["credit"],
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 0,
  },
  {
    id: "canhav.architecture-template",
    family: "shared",
    title: "Architecture template",
    kind: "template",
    href: `${KIT}/ARCHITECTURE.md`,
    rawHref: `${KIT}/ARCHITECTURE.md`,
    why: "The design document, one section per product shape, blanks where a decision is still open.",
    shapes: "all",
    kits: ["credit"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 23,
  },
  {
    id: "canhav.risk-framework",
    family: "shared",
    title: "Risk framework",
    kind: "template",
    href: `${KIT}/RISK_FRAMEWORK.md`,
    rawHref: `${KIT}/RISK_FRAMEWORK.md`,
    why: "A repeatable way to choose oracles, thresholds and caps and to write down why, dated.",
    shapes: ["curated_vault", "collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield", "fixed_rate_yield", ...VAULT_SHAPES],
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 24,
  },
  {
    id: "canhav.role-model",
    family: "shared",
    title: "Role model",
    kind: "template",
    href: `${KIT}/ROLE_MODEL.md`,
    rawHref: `${KIT}/ROLE_MODEL.md`,
    why: "Who can change what, which key holds it, and which rules are enforced rather than promised.",
    shapes: "all",
    steps: ["security"],
    priority: "core",
    readOrder: 25,
  },
  {
    id: "canhav.prelaunch-review",
    family: "shared",
    title: "Pre-launch review",
    kind: "checklist",
    href: `${KIT}/PRELAUNCH_REVIEW.md`,
    rawHref: `${KIT}/PRELAUNCH_REVIEW.md`,
    why: "The twenty-two passes the studio records verdicts for, with what counts as evidence for each.",
    shapes: "all",
    kits: ["credit"],
    steps: ["security", "review"],
    priority: "core",
    readOrder: 27,
  },
  {
    id: "canhav.rate-transparency",
    family: "shared",
    title: "Rate transparency",
    kind: "template",
    href: `${KIT}/RATE_TRANSPARENCY.md`,
    rawHref: `${KIT}/RATE_TRANSPARENCY.md`,
    why: "The nine rates a credit product carries, what each one is, where it comes from and the label to use. No screen shows one number called yield.",
    shapes: CREDIT_AND_VAULTS,
    steps: ["architecture", "security", "review"],
    priority: "core",
    readOrder: 28,
  },
  {
    id: "canhav.cross-protocol-invariants",
    family: "shared",
    title: "Cross-protocol invariants",
    kind: "template",
    href: `${KIT}/CROSS_PROTOCOL_INVARIANTS.md`,
    rawHref: `${KIT}/CROSS_PROTOCOL_INVARIANTS.md`,
    why: "Fourteen statements that hold across the seams, vault share to wrapped unit, wrapped unit to two halves, fixed half to collateral, phrased for a fork of mainnet.",
    shapes: ["fixed_rate_yield", "embedded_fixed_rate", "pt_backed_borrowing", "leveraged_fixed_yield", "yield_token_exposure"],
    steps: ["security"],
    priority: "core",
    readOrder: 29,
  },
  {
    id: "canhav.asset-registry",
    family: "shared",
    title: "Asset registry",
    kind: "template",
    href: `${KIT}/ASSET_REGISTRY.md`,
    rawHref: `${KIT}/ASSET_REGISTRY.md`,
    why: "One registry where every asset points back to what it is built on, underlying, vault, wrapped unit, fixed half, so any agent can walk to the base asset.",
    shapes: CREDIT_AND_VAULTS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "canhav.asset-registry-template",
    family: "shared",
    title: "Asset registry template (JSON)",
    kind: "template",
    href: `${KIT}/ASSET_REGISTRY.template.json`,
    rawHref: `${KIT}/ASSET_REGISTRY.template.json`,
    why: "The registry as a JSON file your tests and your agent can read, with one example entry per layer and nulls where nothing is deployed.",
    shapes: CREDIT_AND_VAULTS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "canhav.strategy-vault-yield-to-fixed-rate",
    family: "shared",
    title: "Strategy note, vault yield to a fixed rate",
    kind: "template",
    href: `${KIT}/strategies/01-vault-yield-to-fixed-rate.md`,
    rawHref: `${KIT}/strategies/01-vault-yield-to-fixed-rate.md`,
    why: "The path from a vault share to a fixed rate, the decisions on the way, what goes wrong and the evidence to keep.",
    shapes: ["fixed_rate_yield", "embedded_fixed_rate", "curated_vault"],
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "canhav.strategy-fixed-half-as-collateral",
    family: "shared",
    title: "Strategy note, borrow against the fixed half",
    kind: "template",
    href: `${KIT}/strategies/02-fixed-half-as-collateral.md`,
    rawHref: `${KIT}/strategies/02-fixed-half-as-collateral.md`,
    why: "The fixed half as collateral in an isolated market, the feed, the threshold, the liquidation gap and the scenarios to write down.",
    shapes: ["pt_backed_borrowing", "leveraged_fixed_yield", "collateral_loans"],
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "canhav.strategy-leveraged-loop",
    family: "shared",
    title: "Strategy note, the leveraged fixed-yield loop",
    kind: "template",
    href: `${KIT}/strategies/03-leveraged-fixed-yield-loop.md`,
    rawHref: `${KIT}/strategies/03-leveraged-fixed-yield-loop.md`,
    why: "The loop, its spread arithmetic, the breakeven borrow rate and the unwind. Read before promising a leveraged rate to anyone.",
    shapes: ["leveraged_fixed_yield"],
    steps: ["basics", "architecture", "security"],
    priority: "core",
    readOrder: 30,
  },
  {
    id: "canhav.strategy-stock-token-credit",
    family: "shared",
    title: "Strategy note, tokenised stock credit to yield",
    kind: "template",
    href: `${KIT}/strategies/04-stock-token-credit-to-yield.md`,
    rawHref: `${KIT}/strategies/04-stock-token-credit-to-yield.md`,
    why: "A tokenised stock as collateral, the loan into a vault, the share wrapped and split. Market hours, corporate actions and transfer rules as risks.",
    shapes: ["collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield", "fixed_rate_yield", "permissioned_vault"],
    steps: ["basics", "architecture", "security"],
    priority: "deep_dive",
  },
  {
    id: "canhav.invariants",
    family: "shared",
    title: "Invariants",
    kind: "template",
    href: `${KIT}/INVARIANTS.md`,
    rawHref: `${KIT}/INVARIANTS.md`,
    why: "Fifteen statements that must always hold for vaults and markets, phrased for Foundry and Medusa.",
    shapes: CREDIT_AND_VAULTS,
    steps: ["security"],
    priority: "recommended",
  },

  // -- CanHav liquidity kit files (M36) -----------------------------------------
  {
    id: "canhav.liquidity-kit-readme",
    family: "shared",
    title: "CanHav liquidity kit",
    kind: "template",
    href: `${LIQUIDITY_KIT}/README.md`,
    rawHref: `${LIQUIDITY_KIT}/README.md`,
    why: "What is in the liquidity kit, which files a vault product and a pool product each use, and how to use it with a coding agent, in one page.",
    shapes: "all",
    kits: ["liquidity"],
    steps: ["basics"],
    priority: "core",
    readOrder: 0,
  },
  {
    id: "canhav.liquidity-kit-skill",
    family: "shared",
    title: "Liquidity kit agent skill",
    kind: "skill",
    href: `${LIQUIDITY_KIT}/SKILL.md`,
    rawHref: `${LIQUIDITY_KIT}/SKILL.md`,
    why: "Install this so your agent loads the pack first, deploys nothing on testnet without recording it in the manifest, and never sends a transaction from intent straight to broadcast.",
    shapes: "all",
    kits: ["liquidity"],
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 0,
  },
  {
    id: "canhav.liquidity-architecture-template",
    family: "shared",
    title: "Liquidity architecture template",
    kind: "template",
    href: `${LIQUIDITY_KIT}/ARCHITECTURE.md`,
    rawHref: `${LIQUIDITY_KIT}/ARCHITECTURE.md`,
    why: "The design document for a vault or a pool product, one section per shape, with the self-deploy step in the environment plan and blanks where a decision is still open.",
    shapes: "all",
    kits: ["liquidity"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 23,
  },
  {
    id: "canhav.liquidity-prelaunch-review",
    family: "shared",
    title: "Liquidity pre-launch review",
    kind: "checklist",
    href: `${LIQUIDITY_KIT}/PRELAUNCH_REVIEW.md`,
    rawHref: `${LIQUIDITY_KIT}/PRELAUNCH_REVIEW.md`,
    why: "The passes the studio records verdicts for on a vault or a pool product, twenty-eight rows each naming its shapes, with what counts as evidence for each.",
    shapes: "all",
    kits: ["liquidity"],
    steps: ["security", "review"],
    priority: "core",
    readOrder: 27,
  },

  // -- standards ---------------------------------------------------------------
  {
    id: "eip.erc-4626",
    family: "shared",
    title: "ERC-4626 tokenized vault standard",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-4626",
    why: "Mandatory reading. Defines assets versus shares, deposit, mint, withdraw, redeem, previews and the accounting conventions every vault inherits.",
    shapes: VAULT_LIKE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 13,
  },
  {
    id: "oz.erc-4626",
    family: "shared",
    title: "OpenZeppelin ERC-4626 guide",
    kind: "docs",
    href: "https://docs.openzeppelin.com/contracts/5.x/erc4626",
    why: "Explains share-price manipulation, inflation and first-depositor attacks, not just the interface.",
    shapes: VAULT_LIKE,
    steps: ["security"],
    priority: "core",
    readOrder: 14,
  },
  {
    id: "eip.erc-5115",
    family: "shared",
    title: "ERC-5115 standardized yield",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-5115",
    why: "The wrapper interface that turns any yield-bearing asset into something a market can split. Your vault shares are one deposit away from it.",
    shapes: ["fixed_rate_yield", "pt_backed_borrowing", "leveraged_fixed_yield", "yield_token_exposure"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 13,
  },
  {
    id: "eip.erc-5095",
    family: "shared",
    title: "ERC-5095 principal token",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-5095",
    why: "The standard shape of a token that redeems for one unit at maturity. Useful when your product must read fixed halves from more than one issuer.",
    shapes: ["fixed_rate_yield", "embedded_fixed_rate", "pt_backed_borrowing", "leveraged_fixed_yield"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "eip.erc-8056",
    family: "shared",
    title: "ERC-8056 scaled UI amounts",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-8056",
    why: "The updatable multiplier a tokenised stock uses to show split-adjusted balances. Apply it once, when reconciling the raw balance with an off-chain price, and never to a feed that is already adjusted, or the collateral is counted twice.",
    shapes: ["collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield", "curated_vault", "permissioned_vault"],
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "eip.erc-7540",
    family: "shared",
    title: "ERC-7540 asynchronous vaults",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-7540",
    why: "Deposits and redemptions that cannot settle atomically. Matters the day your vault holds tokenized real-world assets with settlement windows.",
    shapes: ["curated_vault", "fixed_rate_yield", "permissioned_vault"],
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "eip.erc-5143",
    family: "shared",
    title: "ERC-5143 slippage protection for vaults",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-5143",
    why: "Minimum shares and maximum assets on vault calls. Even if you do not implement it, the idea belongs in your transaction layer.",
    shapes: ["curated_vault", "embedded_earn", "embedded_fixed_rate", ...VAULT_SHAPES],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "eip.eip-2612",
    family: "shared",
    title: "EIP-2612 permit",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-2612",
    why: "Signed approvals instead of a separate approve transaction. One less wallet prompt on every deposit.",
    shapes: APP_FLOWS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.permit2",
    family: "shared",
    title: "Permit2",
    kind: "repo",
    href: "https://github.com/Uniswap/permit2",
    rawHref: "https://raw.githubusercontent.com/Uniswap/permit2/main/README.md",
    why: "Permit-style approvals for tokens that never implemented EIP-2612, plus batched approvals and signature transfers. The Universal Router depends on it, so a pool product deploys it on testnet too.",
    shapes: [...APP_FLOWS, "basic_amm_pool", "concentrated_liquidity_pool", "hook_pool"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "eip.erc-1271",
    family: "shared",
    title: "ERC-1271 contract signatures",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-1271",
    why: "How a smart account verifies a signature. Needed the moment a customer uses a Safe or a treasury contract instead of a plain wallet.",
    shapes: "all",
    steps: ["architecture"],
    priority: "recommended",
  },

  // -- transaction safety and data ------------------------------------------------
  {
    id: "viem.simulate-contract",
    family: "shared",
    title: "viem simulateContract",
    kind: "docs",
    href: "https://viem.sh/docs/contract/simulateContract",
    why: "Simulate, explain, confirm, then execute. Make it the standard pattern for every deposit, withdrawal, borrow and admin call.",
    shapes: "all",
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 15,
  },
  {
    id: "thegraph.robinhood",
    family: "shared",
    title: "The Graph on Robinhood Chain",
    chains: ["robinhood_testnet"],
    kind: "docs",
    href: "https://thegraph.com/docs/en/supported-networks/robinhood/",
    why: "Firehose and Substreams cover mainnet. Your historical layer for TVL, APY, allocations, balances and liquidations can start here instead of a custom indexer. Verify testnet coverage separately.",
    shapes: "all",
    steps: ["architecture"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },

  // -- comparative designs -------------------------------------------------------
  {
    id: "yearn.v3-tech-spec",
    family: "shared",
    title: "Yearn V3 technical specification",
    kind: "docs",
    href: "https://github.com/yearn/yearn-vaults-v3/blob/master/TECH_SPEC.md",
    rawHref: "https://raw.githubusercontent.com/yearn/yearn-vaults-v3/master/TECH_SPEC.md",
    why: "A comparative vault design that separates strategies, accounting, roles, deposit controls and automation. Read it before designing a curator layer of your own.",
    shapes: ["curated_vault", "liquidity_allocator"],
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "euler.earn",
    family: "shared",
    title: "Euler Earn",
    kind: "repo",
    href: "https://github.com/euler-xyz/euler-earn",
    why: "Another vault manager built on the same architecture family. Addresses exchange-rate manipulation, share inflation, zero-share deposits and reentrancy head on.",
    shapes: ["curated_vault", "embedded_earn", ...VAULT_SHAPES],
    steps: ["architecture", "security"],
    priority: "deep_dive",
  },
  {
    id: "euler.vault-kit",
    family: "shared",
    title: "Euler Vault Kit",
    kind: "repo",
    href: "https://github.com/euler-xyz/euler-vault-kit",
    why: "Credit vaults with borrowing, invariant tests included. The best non-Morpho lending codebase to study.",
    shapes: LENDING_LIKE,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "euler.vault-kit-whitepaper",
    family: "shared",
    title: "Euler Vault Kit whitepaper",
    kind: "paper",
    href: "https://github.com/euler-xyz/euler-vault-kit/blob/master/docs/whitepaper.md",
    rawHref: "https://raw.githubusercontent.com/euler-xyz/euler-vault-kit/master/docs/whitepaper.md",
    why: "Account health, vault health, caps, collateral selection, oracle requirements and the risks of illiquid or malicious collateral, explained once.",
    shapes: LENDING_LIKE,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "aave.v3-validation-logic",
    family: "shared",
    title: "Aave V3 ValidationLogic.sol",
    kind: "repo",
    href: "https://github.com/aave-dao/aave-v3-origin/blob/main/src/contracts/protocol/libraries/logic/ValidationLogic.sol",
    why: "A checklist of lending edge cases in one file, from supply caps and frozen reserves to liquidation eligibility and isolation.",
    shapes: LENDING_LIKE,
    steps: ["architecture", "security"],
    priority: "deep_dive",
  },

  // -- oracles ------------------------------------------------------------------
  {
    id: "pyth.best-practices",
    family: "shared",
    title: "Pyth price feed best practices",
    kind: "docs",
    href: "https://docs.pyth.network/price-feeds/best-practices",
    why: "Staleness, latency, confidence intervals, volatility, availability gaps and market hours. The last two matter when collateral tracks a market that closes at night.",
    shapes: [...LENDING_LIKE, "permissioned_vault"],
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 16,
  },
  {
    id: "pyth.morpho-guide",
    family: "shared",
    title: "Use Pyth for Morpho markets",
    kind: "docs",
    href: "https://docs.pyth.network/price-feeds/core/use-pyth-for-morpho",
    why: "A wrapper that implements the market oracle interface over Pyth feeds, with the update scheduling it needs.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 17,
  },
  {
    id: "pyth.morpho-wrapper",
    family: "shared",
    title: "Pyth oracle wrapper repository",
    kind: "repo",
    href: "https://github.com/pyth-network/pyth-morpho-wrapper",
    why: "The contract and factory behind the guide above.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "chainlink.data-feeds",
    family: "shared",
    title: "Chainlink data feeds",
    kind: "docs",
    href: "https://docs.chain.link/data-feeds",
    why: "An independent oracle reference and the guidance on feed quality and choosing the right feed.",
    shapes: [...LENDING_LIKE, "permissioned_vault"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "chainlink.feed-addresses",
    family: "shared",
    title: "Chainlink feed addresses",
    kind: "addresses",
    href: "https://docs.chain.link/data-feeds/price-feeds/addresses",
    why: "Look up whether a feed exists for your chain and asset before you design a market around it.",
    shapes: [...LENDING_LIKE, "permissioned_vault"],
    steps: ["reality"],
    priority: "recommended",
  },

  // -- risk methodology -----------------------------------------------------------
  {
    id: "chaoslabs.aave-v3-methodology",
    family: "shared",
    title: "Chaos Labs risk parameter methodology",
    kind: "paper",
    href: "https://chaoslabs.xyz/resources/chaos_aave_risk_param_methodology.pdf",
    why: "Agent-based simulation for liquidation thresholds, incentives, caps, concentration and bad-debt probability. A model for choosing your own numbers.",
    shapes: ["curated_vault", ...LENDING_LIKE, ...VAULT_SHAPES],
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "llamarisk.debt-ceiling",
    family: "shared",
    title: "LlamaRisk debt ceiling methodology",
    kind: "paper",
    href: "https://llamarisk.com/research/debt-ceiling-methdology",
    why: "Price shock, liquidatable collateral, available liquidity, liquidator profit, exposure limit. The most directly reusable cap methodology.",
    shapes: ["curated_vault", ...LENDING_LIKE, ...VAULT_SHAPES],
    steps: ["security"],
    priority: "recommended",
  },

  // -- security tooling -------------------------------------------------------------
  {
    id: "tob.secure-workflow-skill",
    family: "shared",
    title: "Trail of Bits secure workflow skill",
    kind: "skill",
    href: "https://github.com/trailofbits/skills/blob/main/plugins/building-secure-contracts/skills/secure-workflow-guide/SKILL.md",
    rawHref:
      "https://raw.githubusercontent.com/trailofbits/skills/main/plugins/building-secure-contracts/skills/secure-workflow-guide/SKILL.md",
    why: "Tells a coding agent to run static analysis, standard conformance checks, architecture review, property definition and fuzzing. Rank it right behind the protocol skills.",
    shapes: "all",
    steps: ["security"],
    priority: "core",
    readOrder: 18,
  },
  {
    id: "tob.token-integration",
    family: "shared",
    title: "Token integration checklist",
    kind: "checklist",
    href: "https://github.com/crytic/building-secure-contracts/blob/master/development-guidelines/token_integration.md",
    rawHref:
      "https://raw.githubusercontent.com/crytic/building-secure-contracts/master/development-guidelines/token_integration.md",
    why: "Lending touches tokens with strange behaviour. Run this before approving anything as a vault asset, loan asset or collateral.",
    shapes: "all",
    steps: ["security"],
    priority: "core",
    readOrder: 19,
  },
  {
    id: "tob.token-integration-skill",
    family: "shared",
    title: "Token integration analyzer skill",
    kind: "skill",
    href: "https://github.com/trailofbits/skills/blob/main/plugins/building-secure-contracts/skills/token-integration-analyzer/SKILL.md",
    rawHref:
      "https://raw.githubusercontent.com/trailofbits/skills/main/plugins/building-secure-contracts/skills/token-integration-analyzer/SKILL.md",
    why: "The checklist above as an agent skill, so the review runs the same way every time.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "tob.workflow",
    family: "shared",
    title: "Secure development workflow",
    kind: "checklist",
    href: "https://github.com/crytic/building-secure-contracts/blob/master/development-guidelines/workflow.md",
    rawHref:
      "https://raw.githubusercontent.com/crytic/building-secure-contracts/master/development-guidelines/workflow.md",
    why: "A repeatable process with static analysis, standards validation and property-based testing.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "crytic.medusa-agents",
    family: "shared",
    title: "Medusa fuzzer agent guide",
    kind: "docs",
    href: "https://github.com/crytic/medusa/blob/master/AGENTS.md",
    rawHref: "https://raw.githubusercontent.com/crytic/medusa/master/AGENTS.md",
    why: "A coverage-guided fuzzer with instructions written for coding agents. Assertion, property and optimization testing.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "foundry.invariant-testing",
    family: "shared",
    title: "Foundry invariant testing",
    kind: "docs",
    href: "https://book.getfoundry.sh/forge/invariant-testing",
    why: "Random call sequences against properties that must always hold. Far more useful than line coverage for a vault or a market.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "pashov.skills",
    family: "shared",
    title: "Pashov audit skills",
    kind: "skill",
    href: "https://github.com/pashov/skills",
    why: "A third-party review layer, not an audit replacement. Includes a fuzz-suite generator and a threat-model pass.",
    shapes: "all",
    steps: ["security"],
    priority: "deep_dive",
  },

  // -- roles and custody -----------------------------------------------------------
  {
    id: "oz.access-control",
    family: "shared",
    title: "OpenZeppelin access control and timelocks",
    kind: "docs",
    href: "https://docs.openzeppelin.com/contracts/5.x/access-control",
    why: "Role separation and timelocked admin actions, so users can inspect a change before it executes.",
    shapes: ["curated_vault", "fixed_rate_yield", ...VAULT_SHAPES],
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "safe.starter-kit",
    family: "shared",
    title: "Safe starter kit",
    kind: "docs",
    href: "https://docs.safe.global/sdk/starter-kit",
    why: "Do not leave a curator or market owner role on a single wallet. Smart accounts, multisig transactions and signed messages from one SDK.",
    shapes: ["curated_vault", "collateral_loans", "fixed_rate_yield", "pt_backed_borrowing", ...VAULT_SHAPES],
    steps: ["security", "reality"],
    priority: "recommended",
  },
  {
    id: "safe.docs",
    family: "shared",
    title: "Safe documentation",
    kind: "docs",
    href: "https://docs.safe.global/home/what-is-safe",
    why: "Smart accounts, signer policies, thresholds and recovery. The home for every admin, curator and allocator key a vault or a market hands out.",
    shapes: ["curated_vault", "collateral_loans", "fixed_rate_yield", ...VAULT_SHAPES],
    steps: ["security", "reality"],
    priority: "recommended",
  },
  {
    id: "safe.guards",
    family: "shared",
    title: "Safe guards",
    kind: "docs",
    href: "https://docs.safe.global/advanced/smart-account-guards",
    why: "Inspect a transaction before and after execution and reject policy violations. The seed of a curator policy engine.",
    shapes: ["curated_vault", "fixed_rate_yield", "liquidity_allocator"],
    steps: ["security"],
    priority: "deep_dive",
  },
];
