import { MCP_CONNECT } from "@/content/launch";
import type { KitResource } from "@/lib/kits";

const KIT = `${MCP_CONNECT.baseUrl}/kits/credit`;

const VAULT_LIKE = ["curated_vault", "embedded_earn", "fixed_rate_yield", "embedded_fixed_rate"] as const;
const LENDING_LIKE = ["collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield"] as const;
const APP_FLOWS = [
  "embedded_earn",
  "collateral_loans",
  "embedded_fixed_rate",
  "pt_backed_borrowing",
  "leveraged_fixed_yield",
] as const;

/**
 * Shared family. Standards, security tooling, oracle and risk methodology
 * that sit above every protocol. Ids are immutable.
 */
export const SHARED_RESOURCES: readonly KitResource[] = [
  // -- CanHav kit files -----------------------------------------------------------
  {
    id: "canhav.kit-readme",
    family: "shared",
    title: "CanHav credit kit",
    kind: "template",
    href: `${KIT}/README.md`,
    rawHref: `${KIT}/README.md`,
    why: "What is in the kit and how to use it with a coding agent, in one page.",
    shapes: "all",
    steps: ["basics"],
    priority: "core",
    readOrder: 0,
  },
  {
    id: "canhav.kit-skill",
    family: "shared",
    title: "Credit kit agent skill",
    kind: "skill",
    href: `${KIT}/SKILL.md`,
    rawHref: `${KIT}/SKILL.md`,
    why: "Install this so your agent loads the pack first, works in order, and never sends a transaction from intent straight to broadcast.",
    shapes: "all",
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 0,
  },
  {
    id: "canhav.architecture-template",
    family: "shared",
    title: "Architecture template",
    kind: "template",
    href: `${KIT}/ARCHITECTURE.md`,
    rawHref: `${KIT}/ARCHITECTURE.md`,
    why: "The design document, one section per product shape, blanks where a decision is still open.",
    shapes: "all",
    steps: ["architecture"],
    priority: "core",
    readOrder: 23,
  },
  {
    id: "canhav.risk-framework",
    family: "shared",
    title: "Risk framework",
    kind: "template",
    href: `${KIT}/RISK_FRAMEWORK.md`,
    rawHref: `${KIT}/RISK_FRAMEWORK.md`,
    why: "A repeatable way to choose oracles, thresholds and caps and to write down why, dated.",
    shapes: ["curated_vault", "collateral_loans", "pt_backed_borrowing", "leveraged_fixed_yield", "fixed_rate_yield"],
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 24,
  },
  {
    id: "canhav.role-model",
    family: "shared",
    title: "Role model",
    kind: "template",
    href: `${KIT}/ROLE_MODEL.md`,
    rawHref: `${KIT}/ROLE_MODEL.md`,
    why: "Who can change what, which key holds it, and which rules are enforced rather than promised.",
    shapes: "all",
    steps: ["security"],
    priority: "core",
    readOrder: 25,
  },
  {
    id: "canhav.invariants",
    family: "shared",
    title: "Invariants",
    kind: "template",
    href: `${KIT}/INVARIANTS.md`,
    rawHref: `${KIT}/INVARIANTS.md`,
    why: "Fifteen statements that must always hold for vaults and markets, phrased for Foundry and Medusa.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },

  // -- standards ---------------------------------------------------------------
  {
    id: "eip.erc-4626",
    family: "shared",
    title: "ERC-4626 tokenized vault standard",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-4626",
    why: "Mandatory reading. Defines assets versus shares, deposit, mint, withdraw, redeem, previews and the accounting conventions every vault inherits.",
    shapes: VAULT_LIKE,
    steps: ["architecture"],
    priority: "core",
    readOrder: 13,
  },
  {
    id: "oz.erc-4626",
    family: "shared",
    title: "OpenZeppelin ERC-4626 guide",
    kind: "docs",
    href: "https://docs.openzeppelin.com/contracts/5.x/erc4626",
    why: "Explains share-price manipulation, inflation and first-depositor attacks, not just the interface.",
    shapes: VAULT_LIKE,
    steps: ["security"],
    priority: "core",
    readOrder: 14,
  },
  {
    id: "eip.erc-7540",
    family: "shared",
    title: "ERC-7540 asynchronous vaults",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-7540",
    why: "Deposits and redemptions that cannot settle atomically. Matters the day your vault holds tokenized real-world assets with settlement windows.",
    shapes: ["curated_vault", "fixed_rate_yield"],
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "eip.erc-5143",
    family: "shared",
    title: "ERC-5143 slippage protection for vaults",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-5143",
    why: "Minimum shares and maximum assets on vault calls. Even if you do not implement it, the idea belongs in your transaction layer.",
    shapes: ["curated_vault", "embedded_earn", "embedded_fixed_rate"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "eip.eip-2612",
    family: "shared",
    title: "EIP-2612 permit",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-2612",
    why: "Signed approvals instead of a separate approve transaction. One less wallet prompt on every deposit.",
    shapes: APP_FLOWS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.permit2",
    family: "shared",
    title: "Permit2",
    kind: "repo",
    href: "https://github.com/Uniswap/permit2",
    rawHref: "https://raw.githubusercontent.com/Uniswap/permit2/main/README.md",
    why: "Permit-style approvals for tokens that never implemented EIP-2612, plus batched approvals and signature transfers.",
    shapes: APP_FLOWS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "eip.erc-1271",
    family: "shared",
    title: "ERC-1271 contract signatures",
    kind: "spec",
    href: "https://eips.ethereum.org/EIPS/eip-1271",
    why: "How a smart account verifies a signature. Needed the moment a customer uses a Safe or a treasury contract instead of a plain wallet.",
    shapes: "all",
    steps: ["architecture"],
    priority: "recommended",
  },

  // -- transaction safety and data ------------------------------------------------
  {
    id: "viem.simulate-contract",
    family: "shared",
    title: "viem simulateContract",
    kind: "docs",
    href: "https://viem.sh/docs/contract/simulateContract",
    why: "Simulate, explain, confirm, then execute. Make it the standard pattern for every deposit, withdrawal, borrow and admin call.",
    shapes: "all",
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 15,
  },
  {
    id: "thegraph.robinhood",
    family: "shared",
    title: "The Graph on Robinhood Chain",
    kind: "docs",
    href: "https://thegraph.com/docs/en/supported-networks/robinhood/",
    why: "Firehose and Substreams cover mainnet. Your historical layer for TVL, APY, allocations, balances and liquidations can start here instead of a custom indexer. Verify testnet coverage separately.",
    shapes: "all",
    steps: ["architecture"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },

  // -- comparative designs -------------------------------------------------------
  {
    id: "yearn.v3-tech-spec",
    family: "shared",
    title: "Yearn V3 technical specification",
    kind: "docs",
    href: "https://github.com/yearn/yearn-vaults-v3/blob/master/TECH_SPEC.md",
    rawHref: "https://raw.githubusercontent.com/yearn/yearn-vaults-v3/master/TECH_SPEC.md",
    why: "A comparative vault design that separates strategies, accounting, roles, deposit controls and automation. Read it before designing a curator layer of your own.",
    shapes: ["curated_vault"],
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "euler.earn",
    family: "shared",
    title: "Euler Earn",
    kind: "repo",
    href: "https://github.com/euler-xyz/euler-earn",
    why: "Another vault manager built on the same architecture family. Addresses exchange-rate manipulation, share inflation, zero-share deposits and reentrancy head on.",
    shapes: ["curated_vault", "embedded_earn"],
    steps: ["architecture", "security"],
    priority: "deep_dive",
  },
  {
    id: "euler.vault-kit",
    family: "shared",
    title: "Euler Vault Kit",
    kind: "repo",
    href: "https://github.com/euler-xyz/euler-vault-kit",
    why: "Credit vaults with borrowing, invariant tests included. The best non-Morpho lending codebase to study.",
    shapes: LENDING_LIKE,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "euler.vault-kit-whitepaper",
    family: "shared",
    title: "Euler Vault Kit whitepaper",
    kind: "paper",
    href: "https://github.com/euler-xyz/euler-vault-kit/blob/master/docs/whitepaper.md",
    rawHref: "https://raw.githubusercontent.com/euler-xyz/euler-vault-kit/master/docs/whitepaper.md",
    why: "Account health, vault health, caps, collateral selection, oracle requirements and the risks of illiquid or malicious collateral, explained once.",
    shapes: LENDING_LIKE,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "aave.v3-validation-logic",
    family: "shared",
    title: "Aave V3 ValidationLogic.sol",
    kind: "repo",
    href: "https://github.com/aave-dao/aave-v3-origin/blob/main/src/contracts/protocol/libraries/logic/ValidationLogic.sol",
    why: "A checklist of lending edge cases in one file, from supply caps and frozen reserves to liquidation eligibility and isolation.",
    shapes: LENDING_LIKE,
    steps: ["architecture", "security"],
    priority: "deep_dive",
  },

  // -- oracles ------------------------------------------------------------------
  {
    id: "pyth.best-practices",
    family: "shared",
    title: "Pyth price feed best practices",
    kind: "docs",
    href: "https://docs.pyth.network/price-feeds/best-practices",
    why: "Staleness, latency, confidence intervals, volatility, availability gaps and market hours. The last two matter when collateral tracks a market that closes at night.",
    shapes: LENDING_LIKE,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 16,
  },
  {
    id: "pyth.morpho-guide",
    family: "shared",
    title: "Use Pyth for Morpho markets",
    kind: "docs",
    href: "https://docs.pyth.network/price-feeds/core/use-pyth-for-morpho",
    why: "A wrapper that implements the market oracle interface over Pyth feeds, with the update scheduling it needs.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "core",
    readOrder: 17,
  },
  {
    id: "pyth.morpho-wrapper",
    family: "shared",
    title: "Pyth oracle wrapper repository",
    kind: "repo",
    href: "https://github.com/pyth-network/pyth-morpho-wrapper",
    why: "The contract and factory behind the guide above.",
    shapes: ["collateral_loans", "pt_backed_borrowing"],
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "chainlink.data-feeds",
    family: "shared",
    title: "Chainlink data feeds",
    kind: "docs",
    href: "https://docs.chain.link/data-feeds",
    why: "An independent oracle reference and the guidance on feed quality and choosing the right feed.",
    shapes: LENDING_LIKE,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "chainlink.feed-addresses",
    family: "shared",
    title: "Chainlink feed addresses",
    kind: "addresses",
    href: "https://docs.chain.link/data-feeds/price-feeds/addresses",
    why: "Look up whether a feed exists for your chain and asset before you design a market around it.",
    shapes: LENDING_LIKE,
    steps: ["reality"],
    priority: "recommended",
  },

  // -- risk methodology -----------------------------------------------------------
  {
    id: "chaoslabs.aave-v3-methodology",
    family: "shared",
    title: "Chaos Labs risk parameter methodology",
    kind: "paper",
    href: "https://chaoslabs.xyz/resources/chaos_aave_risk_param_methodology.pdf",
    why: "Agent-based simulation for liquidation thresholds, incentives, caps, concentration and bad-debt probability. A model for choosing your own numbers.",
    shapes: ["curated_vault", ...LENDING_LIKE],
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "llamarisk.debt-ceiling",
    family: "shared",
    title: "LlamaRisk debt ceiling methodology",
    kind: "paper",
    href: "https://llamarisk.com/research/debt-ceiling-methdology",
    why: "Price shock, liquidatable collateral, available liquidity, liquidator profit, exposure limit. The most directly reusable cap methodology.",
    shapes: ["curated_vault", ...LENDING_LIKE],
    steps: ["security"],
    priority: "recommended",
  },

  // -- security tooling -------------------------------------------------------------
  {
    id: "tob.secure-workflow-skill",
    family: "shared",
    title: "Trail of Bits secure workflow skill",
    kind: "skill",
    href: "https://github.com/trailofbits/skills/blob/main/plugins/building-secure-contracts/skills/secure-workflow-guide/SKILL.md",
    rawHref:
      "https://raw.githubusercontent.com/trailofbits/skills/main/plugins/building-secure-contracts/skills/secure-workflow-guide/SKILL.md",
    why: "Tells a coding agent to run static analysis, standard conformance checks, architecture review, property definition and fuzzing. Rank it right behind the protocol skills.",
    shapes: "all",
    steps: ["security"],
    priority: "core",
    readOrder: 18,
  },
  {
    id: "tob.token-integration",
    family: "shared",
    title: "Token integration checklist",
    kind: "checklist",
    href: "https://github.com/crytic/building-secure-contracts/blob/master/development-guidelines/token_integration.md",
    rawHref:
      "https://raw.githubusercontent.com/crytic/building-secure-contracts/master/development-guidelines/token_integration.md",
    why: "Lending touches tokens with strange behaviour. Run this before approving anything as a vault asset, loan asset or collateral.",
    shapes: "all",
    steps: ["security"],
    priority: "core",
    readOrder: 19,
  },
  {
    id: "tob.token-integration-skill",
    family: "shared",
    title: "Token integration analyzer skill",
    kind: "skill",
    href: "https://github.com/trailofbits/skills/blob/main/plugins/building-secure-contracts/skills/token-integration-analyzer/SKILL.md",
    rawHref:
      "https://raw.githubusercontent.com/trailofbits/skills/main/plugins/building-secure-contracts/skills/token-integration-analyzer/SKILL.md",
    why: "The checklist above as an agent skill, so the review runs the same way every time.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "tob.workflow",
    family: "shared",
    title: "Secure development workflow",
    kind: "checklist",
    href: "https://github.com/crytic/building-secure-contracts/blob/master/development-guidelines/workflow.md",
    rawHref:
      "https://raw.githubusercontent.com/crytic/building-secure-contracts/master/development-guidelines/workflow.md",
    why: "A repeatable process with static analysis, standards validation and property-based testing.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "crytic.medusa-agents",
    family: "shared",
    title: "Medusa fuzzer agent guide",
    kind: "docs",
    href: "https://github.com/crytic/medusa/blob/master/AGENTS.md",
    rawHref: "https://raw.githubusercontent.com/crytic/medusa/master/AGENTS.md",
    why: "A coverage-guided fuzzer with instructions written for coding agents. Assertion, property and optimization testing.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "foundry.invariant-testing",
    family: "shared",
    title: "Foundry invariant testing",
    kind: "docs",
    href: "https://book.getfoundry.sh/forge/invariant-testing",
    why: "Random call sequences against properties that must always hold. Far more useful than line coverage for a vault or a market.",
    shapes: "all",
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "pashov.skills",
    family: "shared",
    title: "Pashov audit skills",
    kind: "skill",
    href: "https://github.com/pashov/skills",
    why: "A third-party review layer, not an audit replacement. Includes a fuzz-suite generator and a threat-model pass.",
    shapes: "all",
    steps: ["security"],
    priority: "deep_dive",
  },

  // -- roles and custody -----------------------------------------------------------
  {
    id: "oz.access-control",
    family: "shared",
    title: "OpenZeppelin access control and timelocks",
    kind: "docs",
    href: "https://docs.openzeppelin.com/contracts/5.x/access-control",
    why: "Role separation and timelocked admin actions, so users can inspect a change before it executes.",
    shapes: ["curated_vault", "fixed_rate_yield"],
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "safe.starter-kit",
    family: "shared",
    title: "Safe starter kit",
    kind: "docs",
    href: "https://docs.safe.global/sdk/starter-kit",
    why: "Do not leave a curator or market owner role on a single wallet. Smart accounts, multisig transactions and signed messages from one SDK.",
    shapes: ["curated_vault", "collateral_loans", "fixed_rate_yield", "pt_backed_borrowing"],
    steps: ["security", "reality"],
    priority: "recommended",
  },
  {
    id: "safe.guards",
    family: "shared",
    title: "Safe guards",
    kind: "docs",
    href: "https://docs.safe.global/advanced/smart-account-guards",
    why: "Inspect a transaction before and after execution and reject policy violations. The seed of a curator policy engine.",
    shapes: ["curated_vault", "fixed_rate_yield"],
    steps: ["security"],
    priority: "deep_dive",
  },
];
