import { MCP_CONNECT } from "@/content/launch";
import type { KitResource } from "@/lib/kits";

const DOCS = "https://developers.uniswap.org/docs";
const GH = "https://github.com/Uniswap";
const RAW = "https://raw.githubusercontent.com/Uniswap";
const AI = `${GH}/uniswap-ai/blob/main/packages/plugins`;
const AI_RAW = `${RAW}/uniswap-ai/main/packages/plugins`;
const HOOKS_PUBLIC = `${GH}/v4-hooks-public/blob/main`;
const KIT = `${MCP_CONNECT.baseUrl}/kits/liquidity/uniswap`;

const POOLS = ["basic_amm_pool", "concentrated_liquidity_pool", "hook_pool"] as const;
/** Everything on the singleton, with or without a hook. */
const V4 = ["concentrated_liquidity_pool", "hook_pool"] as const;
const V2 = ["basic_amm_pool"] as const;
const HOOKS = ["hook_pool"] as const;

/**
 * Uniswap family, the pools pack. The protocol is live on Robinhood Chain
 * mainnet 4663 (v2, v3, v4, Universal Router, Permit2) and has no
 * deployment on testnet 46630, so the contract repositories carry
 * self_deploy, a team puts the stack on testnet itself and records it in its
 * own manifest, and every canonical address record carries mainnet_only. The
 * docs site serves markdown at the same path with ".md" appended, which is
 * what rawHref carries. Ids are immutable.
 */
export const UNISWAP_RESOURCES: readonly KitResource[] = [
  // -- agent skills ---------------------------------------------------------
  {
    id: "uniswap.skill-hook-generator",
    family: "uniswap",
    title: "Hook generator skill",
    kind: "skill",
    href: `${AI}/uniswap-hooks/skills/v4-hook-generator/SKILL.md`,
    rawHref: `${AI_RAW}/uniswap-hooks/skills/v4-hook-generator/SKILL.md`,
    why: "Instructions for a coding agent that scaffolds a hook, picks its permissions, mines its address and writes the first tests. Load it before writing a hook by hand.",
    shapes: HOOKS,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 1,
  },
  {
    id: "uniswap.skill-security-foundations",
    family: "uniswap",
    title: "Hook security foundations skill",
    kind: "skill",
    href: `${AI}/uniswap-hooks/skills/v4-security-foundations/SKILL.md`,
    rawHref: `${AI_RAW}/uniswap-hooks/skills/v4-security-foundations/SKILL.md`,
    why: "The review pass for a hook as an agent skill, from permission bits and reentrancy to delta accounting. Run it on every hook before a fork test.",
    shapes: HOOKS,
    steps: ["security", "review"],
    priority: "core",
    readOrder: 2,
  },
  {
    id: "uniswap.skill-v4-sdk",
    family: "uniswap",
    title: "v4 SDK integration skill",
    kind: "skill",
    href: `${AI}/uniswap-trading/skills/v4-sdk-integration/SKILL.md`,
    rawHref: `${AI_RAW}/uniswap-trading/skills/v4-sdk-integration/SKILL.md`,
    why: "How an agent builds pool keys, positions, quotes and swaps through the SDK against a chain of your choosing. The fastest route from a deployed singleton to a working front end.",
    shapes: V4,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 1,
  },
  {
    id: "uniswap.skill-lp-integration",
    family: "uniswap",
    title: "Liquidity provision skill",
    kind: "skill",
    href: `${AI}/uniswap-trading/skills/lp-integration/SKILL.md`,
    rawHref: `${AI_RAW}/uniswap-trading/skills/lp-integration/SKILL.md`,
    why: "Adding, changing and removing liquidity across protocol versions, written for a coding agent. Covers the ratio and range mistakes that cost first providers money.",
    shapes: POOLS,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 2,
  },
  {
    id: "uniswap.skill-swap-integration",
    family: "uniswap",
    title: "Swap integration skill",
    kind: "skill",
    href: `${AI}/uniswap-trading/skills/swap-integration/SKILL.md`,
    rawHref: `${AI_RAW}/uniswap-trading/skills/swap-integration/SKILL.md`,
    why: "Quoting and executing swaps through the router with slippage bounds and deadlines. The user side of a pool once it exists.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.skill-viem",
    family: "uniswap",
    title: "viem integration skill",
    kind: "skill",
    href: `${AI}/uniswap-viem/skills/viem-integration/SKILL.md`,
    rawHref: `${AI_RAW}/uniswap-viem/skills/viem-integration/SKILL.md`,
    why: "Reading pool state and sending transactions with viem against your own chain configuration. What you use on testnet 46630, where the hosted routing does not reach.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.skill-permissioned-pools",
    family: "uniswap",
    title: "Permissioned pools deployer skill",
    kind: "skill",
    href: `${AI}/uniswap-permissioned-pools/skills/permissioned-pools-deployer/SKILL.md`,
    rawHref: `${AI_RAW}/uniswap-permissioned-pools/skills/permissioned-pools-deployer/SKILL.md`,
    why: "Deploying a pool whose hook gates who may trade or provide. The pattern for a pool over a transfer-restricted asset such as a tokenised stock.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.ai-repo",
    family: "uniswap",
    title: "Uniswap AI repository",
    kind: "repo",
    href: `${GH}/uniswap-ai`,
    rawHref: `${RAW}/uniswap-ai/main/README.md`,
    why: "Every skill and plugin the protocol publishes for coding agents, installable as one plugin, with the evaluation suites they are tested against.",
    shapes: POOLS,
    steps: ["basics"],
    priority: "core",
    readOrder: 4,
  },
  {
    id: "uniswap.ai-skills-docs",
    family: "uniswap",
    title: "Uniswap AI skills overview",
    kind: "docs",
    href: `${DOCS}/uniswap-ai/skills`,
    rawHref: `${DOCS}/uniswap-ai/skills.md`,
    why: "What each skill does and how the plugins are meant to be combined. Read before choosing which ones to install.",
    shapes: POOLS,
    steps: ["basics"],
    priority: "recommended",
  },
  {
    id: "uniswap.robinhood-chain-template",
    family: "uniswap",
    title: "Robinhood Chain template for the agent skills",
    chains: ["robinhood_testnet"],
    kind: "docs",
    href: `${AI}/uniswap-trading-tools/references/robinhood-chain.md`,
    rawHref: `${AI_RAW}/uniswap-trading-tools/references/robinhood-chain.md`,
    why: "The chain template the skills read for mainnet 4663, with the deployed contracts, the tradable set, market-hours caveats and the note that there is no bridge to fund a wallet. Your testnet 46630 template follows the same shape.",
    shapes: POOLS,
    steps: ["architecture", "reality"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "uniswap.driver-chains",
    family: "uniswap",
    title: "Chain templates reference",
    kind: "docs",
    href: `${AI}/uniswap-driver/references/chains.md`,
    rawHref: `${AI_RAW}/uniswap-driver/references/chains.md`,
    why: "How the skills resolve a target chain, which fields a template must carry and how to add one. The file to copy when you write the 46630 template.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "deep_dive",
  },

  // -- docs for agents, deployments, the monorepo ------------------------------
  {
    id: "uniswap.llms",
    family: "uniswap",
    title: "Uniswap docs for agents (llms.txt)",
    kind: "docs",
    href: "https://developers.uniswap.org/llms.txt",
    rawHref: "https://developers.uniswap.org/llms-full.txt",
    why: "An index of every docs page plus the whole corpus as one file. Point your agent here so it stops inventing interface details.",
    shapes: POOLS,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 3,
  },
  {
    id: "uniswap.docs",
    family: "uniswap",
    title: "How Uniswap works",
    kind: "docs",
    href: `${DOCS}/get-started/concepts/how-uniswap-works`,
    rawHref: `${DOCS}/get-started/concepts/how-uniswap-works.md`,
    why: "The automated market maker across every protocol version in one page. The vocabulary the rest of the pack assumes.",
    shapes: POOLS,
    steps: ["basics"],
    priority: "core",
    readOrder: 5,
  },
  {
    id: "uniswap.contracts-repo",
    family: "uniswap",
    title: "Contracts monorepo and deployment tooling",
    kind: "repo",
    href: `${GH}/contracts`,
    rawHref: `${RAW}/contracts/main/README.md`,
    why: "The protocol's own deployment machinery for every version, with the deployment records per chain. The starting point for putting the stack on testnet 46630 yourself.",
    shapes: POOLS,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 6,
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.deployments-4663",
    family: "uniswap",
    title: "Robinhood Chain 4663 deployment record",
    chains: ["robinhood_testnet"],
    kind: "addresses",
    href: `${GH}/contracts/blob/main/deployments/4663.md`,
    rawHref: `${RAW}/contracts/main/deployments/json/4663.json`,
    why: "The canonical mainnet addresses for the v2 factory and router, the v3 factory and position manager, the v4 pool manager, position manager, quoter and state view, Permit2 and the Universal Router, with the deployment history. Reference only, never reuse them on testnet 46630.",
    shapes: POOLS,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 7,
    flags: ["mainnet_only"],
  },
  {
    id: "uniswap.v4-deployments-docs",
    family: "uniswap",
    title: "v4 deployments by chain",
    kind: "addresses",
    href: `${DOCS}/protocols/v4/deployments`,
    rawHref: `${DOCS}/protocols/v4/deployments.md`,
    why: "The docs table of v4 addresses per chain, Robinhood Chain included, each linked to the explorer. Confirms what the monorepo record says before you rely on it.",
    shapes: V4,
    steps: ["reality"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "uniswap.v3-deployments-robinhood",
    family: "uniswap",
    title: "v3 deployments on Robinhood Chain",
    chains: ["robinhood_testnet"],
    kind: "addresses",
    href: `${DOCS}/protocols/v3/deployments/v3-robinhood-chain-deployments`,
    rawHref: `${DOCS}/protocols/v3/deployments/v3-robinhood-chain-deployments.md`,
    why: "The v3 factory, position manager, quoter and router on mainnet 4663, for a team that studies or integrates v3 rather than v4.",
    shapes: V4,
    steps: ["reality"],
    priority: "deep_dive",
    flags: ["mainnet_only"],
  },
  {
    id: "uniswap.sdks-repo",
    family: "uniswap",
    title: "SDKs repository",
    kind: "repo",
    href: `${GH}/sdks`,
    rawHref: `${RAW}/sdks/main/README.md`,
    why: "sdk-core plus the v2, v3 and v4 SDKs in one monorepo. Pin a version and read the package for your protocol version.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.sdks-overview",
    family: "uniswap",
    title: "SDKs overview",
    kind: "docs",
    href: `${DOCS}/sdks/overview`,
    rawHref: `${DOCS}/sdks/overview.md`,
    why: "Which SDK does what, and which ones a pool product actually needs. sdk-core for every shape, then the v2 or v4 package.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "recommended",
  },

  // -- Basic AMM pool (v2) ------------------------------------------------------
  {
    id: "uniswap.v2-core",
    family: "uniswap",
    title: "v2 core repository",
    kind: "repo",
    href: `${GH}/v2-core`,
    rawHref: `${RAW}/v2-core/master/README.md`,
    why: "The factory and the pair, unchanged since 2020. What you deploy on testnet 46630 to have a constant-product pool at all.",
    shapes: V2,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 8,
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.v2-periphery",
    family: "uniswap",
    title: "v2 periphery repository",
    kind: "repo",
    href: `${GH}/v2-periphery`,
    rawHref: `${RAW}/v2-periphery/master/README.md`,
    why: "The router your users go through and the library that computes amounts and pair addresses. Deploy it with a wrapped native token on testnet.",
    shapes: V2,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 9,
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.v2-factory-source",
    family: "uniswap",
    title: "UniswapV2Factory.sol",
    kind: "repo",
    href: `${GH}/v2-core/blob/master/contracts/UniswapV2Factory.sol`,
    rawHref: `${RAW}/v2-core/master/contracts/UniswapV2Factory.sol`,
    why: "Creates one pair per token combination and holds the protocol fee switch. Short enough to read in full.",
    shapes: V2,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-pair-source",
    family: "uniswap",
    title: "UniswapV2Pair.sol",
    kind: "repo",
    href: `${GH}/v2-core/blob/master/contracts/UniswapV2Pair.sol`,
    rawHref: `${RAW}/v2-core/master/contracts/UniswapV2Pair.sol`,
    why: "The constant product, the fungible liquidity token, the minimum liquidity burn and the cumulative price oracle in one contract.",
    shapes: V2,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-router-source",
    family: "uniswap",
    title: "UniswapV2Router02.sol",
    kind: "repo",
    href: `${GH}/v2-periphery/blob/master/contracts/UniswapV2Router02.sol`,
    rawHref: `${RAW}/v2-periphery/master/contracts/UniswapV2Router02.sol`,
    why: "Adds liquidity at the right ratio, swaps along a path and enforces minimum amounts and deadlines. The reason not to send tokens to a pair by hand.",
    shapes: V2,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-overview",
    family: "uniswap",
    title: "v2 protocol overview",
    kind: "docs",
    href: `${DOCS}/protocols/v2/overview`,
    rawHref: `${DOCS}/protocols/v2/overview.md`,
    why: "Where v2 sits today and why teams still start with it. The classic pair is the whole product for a basic pool.",
    shapes: V2,
    steps: ["basics"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-architecture",
    family: "uniswap",
    title: "v2 architecture and pools",
    kind: "docs",
    href: `${DOCS}/protocols/v2/concepts/architecture`,
    rawHref: `${DOCS}/protocols/v2/concepts/architecture.md`,
    why: "Factory, pair, router and the constant-product rule, with the liquidity token explained. The design document for a basic pool is mostly this page.",
    shapes: V2,
    steps: ["architecture"],
    priority: "core",
    readOrder: 10,
  },
  {
    id: "uniswap.v2-providing-liquidity",
    family: "uniswap",
    title: "v2 providing liquidity guide",
    kind: "docs",
    href: `${DOCS}/protocols/v2/guides/providing-liquidity`,
    rawHref: `${DOCS}/protocols/v2/guides/providing-liquidity.md`,
    why: "Deposit both sides at the current ratio through the router, or the first trader takes the difference. The guide your seed transaction must follow.",
    shapes: V2,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 11,
  },
  {
    id: "uniswap.v2-swapping",
    family: "uniswap",
    title: "v2 swapping guide",
    kind: "docs",
    href: `${DOCS}/protocols/v2/guides/swapping`,
    rawHref: `${DOCS}/protocols/v2/guides/swapping.md`,
    why: "Exact input and exact output swaps through the router, with the minimum-out and deadline arguments that protect a user from a moving pool.",
    shapes: V2,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-getting-started",
    family: "uniswap",
    title: "v2 getting started",
    kind: "docs",
    href: `${DOCS}/protocols/v2/guides/getting-started`,
    rawHref: `${DOCS}/protocols/v2/guides/getting-started.md`,
    why: "The smart contract integration path for v2, from importing the interfaces to calling a pair.",
    shapes: V2,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-pricing",
    family: "uniswap",
    title: "v2 pricing",
    kind: "docs",
    href: `${DOCS}/protocols/v2/concepts/pricing`,
    rawHref: `${DOCS}/protocols/v2/concepts/pricing.md`,
    why: "How a swap moves the price along the curve and what price impact means for a thin pool. Read before choosing how much to seed.",
    shapes: V2,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-understanding-returns",
    family: "uniswap",
    title: "Understanding returns as a liquidity provider",
    kind: "docs",
    href: `${DOCS}/protocols/v2/concepts/understanding-returns`,
    rawHref: `${DOCS}/protocols/v2/concepts/understanding-returns.md`,
    why: "Fees against divergence loss, explained for the classic pair. The disclosure a provider needs before the first deposit, whichever version you run.",
    shapes: POOLS,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-sdk",
    family: "uniswap",
    title: "v2 SDK overview",
    kind: "docs",
    href: `${DOCS}/sdks/v2/overview`,
    rawHref: `${DOCS}/sdks/v2/overview.md`,
    why: "Pair, route and trade objects for a front end on the classic pair, with the getting started guide beside it.",
    shapes: V2,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-sdk-getting-started",
    family: "uniswap",
    title: "v2 SDK getting started",
    kind: "docs",
    href: `${DOCS}/sdks/v2/guides/getting-started`,
    rawHref: `${DOCS}/sdks/v2/guides/getting-started.md`,
    why: "Install, fetch pair data and build the first trade against your own chain configuration.",
    shapes: V2,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.v2-whitepaper",
    family: "uniswap",
    title: "v2 whitepaper",
    kind: "paper",
    href: "https://app.uniswap.org/whitepaper.pdf",
    why: "The constant product, the fee accrual into reserves and the cumulative price oracle, with the reasoning. Short, and worth reading before the code.",
    shapes: POOLS,
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v2-audits",
    family: "uniswap",
    title: "v2 audits",
    kind: "docs",
    href: `${DOCS}/protocols/v2/audits`,
    rawHref: `${DOCS}/protocols/v2/audits.md`,
    why: "What was checked in the core you are forking, so your own review starts where theirs ended.",
    shapes: V2,
    steps: ["security"],
    priority: "deep_dive",
  },

  // -- Concentrated liquidity and hooks (v4) -------------------------------------
  {
    id: "uniswap.v4-core",
    family: "uniswap",
    title: "v4 core repository",
    kind: "repo",
    href: `${GH}/v4-core`,
    rawHref: `${RAW}/v4-core/main/README.md`,
    why: "The singleton pool manager, the libraries and the audits. What you deploy on testnet 46630 to have a concentrated pool at all.",
    shapes: V4,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 8,
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.v4-periphery",
    family: "uniswap",
    title: "v4 periphery repository",
    kind: "repo",
    href: `${GH}/v4-periphery`,
    rawHref: `${RAW}/v4-periphery/main/README.md`,
    why: "Position manager, quoter, state view and the hook test helpers. Deploy it beside the core and record every address.",
    shapes: V4,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 9,
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.v4-overview",
    family: "uniswap",
    title: "v4 protocol overview",
    kind: "docs",
    href: `${DOCS}/protocols/v4/overview`,
    rawHref: `${DOCS}/protocols/v4/overview.md`,
    why: "The singleton, flash accounting, native currency and hooks in one page. The vocabulary for everything under this shape.",
    shapes: V4,
    steps: ["basics"],
    priority: "core",
    readOrder: 10,
  },
  {
    id: "uniswap.v4-poolmanager-concept",
    family: "uniswap",
    title: "The pool manager",
    kind: "docs",
    href: `${DOCS}/protocols/v4/concepts/poolmanager`,
    rawHref: `${DOCS}/protocols/v4/concepts/poolmanager.md`,
    why: "One contract holds every pool, keyed by the two currencies, the fee, the tick spacing and the hook. What a pool id is and why initialisation is cheap.",
    shapes: V4,
    steps: ["architecture"],
    priority: "core",
    readOrder: 11,
  },
  {
    id: "uniswap.v4-concentrated-liquidity",
    family: "uniswap",
    title: "Concentrated liquidity",
    kind: "docs",
    href: `${DOCS}/get-started/concepts/liquidity-providers/concentrated-liquidity`,
    rawHref: `${DOCS}/get-started/concepts/liquidity-providers/concentrated-liquidity.md`,
    why: "Ranges, ticks and what happens to a position when the price leaves its range. The idea behind every parameter in a pool key.",
    shapes: V4,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 12,
  },
  {
    id: "uniswap.v4-create-pool",
    family: "uniswap",
    title: "Create a v4 pool",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/create-pool`,
    rawHref: `${DOCS}/protocols/v4/guides/create-pool.md`,
    why: "The pool key, the starting price and the first position in one transaction through the position manager. The atomic path is the default because an initialised empty pool can be priced by whoever comes first.",
    shapes: V4,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 13,
  },
  {
    id: "uniswap.v4-sdk-create-pool",
    family: "uniswap",
    title: "Create a pool with the v4 SDK",
    kind: "docs",
    href: `${DOCS}/sdks/v4/guides/create-pool`,
    rawHref: `${DOCS}/sdks/v4/guides/create-pool.md`,
    why: "The same atomic initialise and mint from TypeScript, with the encoding the position manager expects.",
    shapes: V4,
    steps: ["architecture"],
    priority: "core",
    readOrder: 14,
  },
  {
    id: "uniswap.v4-mint-position",
    family: "uniswap",
    title: "Mint a position",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/managing-liquidity/mint-position`,
    rawHref: `${DOCS}/protocols/v4/guides/managing-liquidity/mint-position.md`,
    why: "Lower tick, upper tick, liquidity amount and the two maximum amounts, encoded as position manager actions. The provider's transaction.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-position-manager-guide",
    family: "uniswap",
    title: "The position manager",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/position-manager`,
    rawHref: `${DOCS}/protocols/v4/guides/position-manager.md`,
    why: "How positions are represented, the action encoding and the settle and take steps that close the accounting.",
    shapes: V4,
    steps: ["architecture"],
    priority: "core",
    readOrder: 15,
  },
  {
    id: "uniswap.v4-state-view-guide",
    family: "uniswap",
    title: "Read pool state with StateView",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/state-view`,
    rawHref: `${DOCS}/protocols/v4/guides/state-view.md`,
    why: "Price, liquidity, ticks and fee growth read from the lens instead of decoding the pool manager's storage yourself.",
    shapes: V4,
    steps: ["architecture"],
    priority: "core",
    readOrder: 16,
  },
  {
    id: "uniswap.v4-routing",
    family: "uniswap",
    title: "Swap routing in v4",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/swapping/routing`,
    rawHref: `${DOCS}/protocols/v4/guides/swapping/routing.md`,
    why: "Single and multi-hop swaps through the Universal Router with the actions a v4 swap needs. The user side once the pool exists.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-sdk",
    family: "uniswap",
    title: "v4 SDK overview",
    kind: "docs",
    href: `${DOCS}/sdks/v4/overview`,
    rawHref: `${DOCS}/sdks/v4/overview.md`,
    why: "Pools, positions, quotes and swaps for a front end on the singleton, with guides for each.",
    shapes: V4,
    steps: ["architecture"],
    priority: "core",
    readOrder: 17,
  },
  {
    id: "uniswap.v4-sdk-quoting",
    family: "uniswap",
    title: "Quoting with the v4 SDK",
    kind: "docs",
    href: `${DOCS}/sdks/v4/guides/swapping/quoting`,
    rawHref: `${DOCS}/sdks/v4/guides/swapping/quoting.md`,
    why: "Exact input and exact output quotes from the quoter before a swap is sent. Simulate, explain, confirm, execute.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-flash-accounting",
    family: "uniswap",
    title: "Flash accounting",
    kind: "docs",
    href: `${DOCS}/protocols/v4/concepts/flash-accounting`,
    rawHref: `${DOCS}/protocols/v4/concepts/flash-accounting.md`,
    why: "Balances net out inside one unlock and must settle to zero by the end. Why a hook or a router can move tokens once instead of per step, and why a wrong delta reverts.",
    shapes: V4,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-unlock-deltas",
    family: "uniswap",
    title: "Unlock callback and deltas",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/unlock-callback-and-deltas`,
    rawHref: `${DOCS}/protocols/v4/guides/unlock-callback-and-deltas.md`,
    why: "The callback pattern every custom router and hook lives inside, and how deltas are settled and taken.",
    shapes: V4,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-erc-6909",
    family: "uniswap",
    title: "ERC-6909 claims",
    kind: "docs",
    href: `${DOCS}/protocols/v4/concepts/erc-6909`,
    rawHref: `${DOCS}/protocols/v4/concepts/erc-6909.md`,
    why: "Claim tokens inside the pool manager that save transfers for frequent traders and hooks. Optional, but it shows up in the accounting.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.v4-vs-v3",
    family: "uniswap",
    title: "v4 compared with v3",
    kind: "docs",
    href: `${DOCS}/protocols/v4/concepts/v4-vs-v3`,
    rawHref: `${DOCS}/protocols/v4/concepts/v4-vs-v3.md`,
    why: "What changed and what did not. The page to read before deciding to study v3 at all.",
    shapes: V4,
    steps: ["basics"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-poolmanager-source",
    family: "uniswap",
    title: "PoolManager.sol",
    kind: "repo",
    href: `${GH}/v4-core/blob/main/src/PoolManager.sol`,
    rawHref: `${RAW}/v4-core/main/src/PoolManager.sol`,
    why: "The singleton itself, with initialise, modify liquidity, swap, donate, settle and take. Read it with the interface beside it.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-ipoolmanager-source",
    family: "uniswap",
    title: "IPoolManager.sol",
    kind: "repo",
    href: `${GH}/v4-core/blob/main/src/interfaces/IPoolManager.sol`,
    rawHref: `${RAW}/v4-core/main/src/interfaces/IPoolManager.sol`,
    why: "The interface and its events. What your indexer and your tests listen to.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-pool-library",
    family: "uniswap",
    title: "Pool.sol",
    kind: "repo",
    href: `${GH}/v4-core/blob/main/src/libraries/Pool.sol`,
    rawHref: `${RAW}/v4-core/main/src/libraries/Pool.sol`,
    why: "The per-pool state and the swap loop across ticks. Where the concentrated-liquidity arithmetic actually lives.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.v4-tickmath",
    family: "uniswap",
    title: "TickMath.sol",
    kind: "repo",
    href: `${GH}/v4-core/blob/main/src/libraries/TickMath.sol`,
    rawHref: `${RAW}/v4-core/main/src/libraries/TickMath.sol`,
    why: "Tick to square-root price and back. You need it to turn a human price into the numbers a pool key and a position take.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-liquidity-amounts",
    family: "uniswap",
    title: "LiquidityAmounts.sol",
    kind: "repo",
    href: `${GH}/v4-periphery/blob/main/src/libraries/LiquidityAmounts.sol`,
    rawHref: `${RAW}/v4-periphery/main/src/libraries/LiquidityAmounts.sol`,
    why: "Token amounts to liquidity and back for a range. The arithmetic behind the two maximum amounts on a mint.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-position-manager-source",
    family: "uniswap",
    title: "PositionManager.sol",
    kind: "repo",
    href: `${GH}/v4-periphery/blob/main/src/PositionManager.sol`,
    rawHref: `${RAW}/v4-periphery/main/src/PositionManager.sol`,
    why: "The contract that mints, changes and burns positions and initialises pools atomically. Deployed by you on testnet.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.v4-state-view-source",
    family: "uniswap",
    title: "StateView.sol",
    kind: "repo",
    href: `${GH}/v4-periphery/blob/main/src/lens/StateView.sol`,
    rawHref: `${RAW}/v4-periphery/main/src/lens/StateView.sol`,
    why: "The read lens over the pool manager. Small, and one of the addresses your manifest must carry.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.v4-quoter-source",
    family: "uniswap",
    title: "V4Quoter.sol",
    kind: "repo",
    href: `${GH}/v4-periphery/blob/main/src/lens/V4Quoter.sol`,
    rawHref: `${RAW}/v4-periphery/main/src/lens/V4Quoter.sol`,
    why: "Quotes by simulating the swap and reverting with the result. Never call it in a transaction, only from a read.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.v4-whitepaper",
    family: "uniswap",
    title: "v4 whitepaper",
    kind: "paper",
    href: "https://uniswap.org/whitepaper-v4.pdf",
    why: "The singleton, flash accounting, hooks and native currency, with the reasoning behind each. Read after the overview.",
    shapes: V4,
    steps: ["basics", "architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v3-whitepaper",
    family: "uniswap",
    title: "v3 whitepaper",
    kind: "paper",
    href: "https://uniswap.org/whitepaper-v3.pdf",
    why: "Where concentrated liquidity, ticks and range positions were defined. v4 inherits the mathematics unchanged.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v3-core",
    family: "uniswap",
    title: "v3 core repository",
    kind: "repo",
    href: `${GH}/v3-core`,
    rawHref: `${RAW}/v3-core/main/README.md`,
    why: "The previous concentrated-liquidity implementation, one pool per contract. Reference reading, or the thing to deploy if you specifically study v3.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.v3-periphery",
    family: "uniswap",
    title: "v3 periphery repository",
    kind: "repo",
    href: `${GH}/v3-periphery`,
    why: "The v3 position manager, router and quoter. Reference for teams comparing the two position models.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.deploy-v3",
    family: "uniswap",
    title: "deploy-v3 CLI",
    kind: "tool",
    href: `${GH}/deploy-v3`,
    rawHref: `${RAW}/deploy-v3/main/README.md`,
    why: "Deploys the whole v3 suite to any EVM chain and writes the resulting addresses to a state file. The model for your own 46630 manifest even if you deploy v4.",
    shapes: V4,
    steps: ["reality"],
    priority: "deep_dive",
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.v3-sdk",
    family: "uniswap",
    title: "v3 SDK overview",
    kind: "docs",
    href: `${DOCS}/sdks/v3/overview`,
    rawHref: `${DOCS}/sdks/v3/overview.md`,
    why: "Still the clearest guides for quoting, routing, ranges and position maths, most of which carry to v4.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.v3-overview",
    family: "uniswap",
    title: "v3 protocol overview",
    kind: "docs",
    href: `${DOCS}/protocols/v3/overview`,
    rawHref: `${DOCS}/protocols/v3/overview.md`,
    why: "The version that introduced ranges, for readers who want the history before the singleton.",
    shapes: V4,
    steps: ["basics"],
    priority: "deep_dive",
  },

  // -- hooks ------------------------------------------------------------------
  {
    id: "uniswap.v4-hooks-concept",
    family: "uniswap",
    title: "Hooks",
    kind: "docs",
    href: `${DOCS}/protocols/v4/concepts/hooks`,
    rawHref: `${DOCS}/protocols/v4/concepts/hooks.md`,
    why: "The callbacks around initialise, swap, liquidity changes and donations, the permission bits in the address, and the one-hook-per-pool rule.",
    shapes: HOOKS,
    steps: ["basics", "architecture"],
    priority: "core",
    readOrder: 18,
  },
  {
    id: "uniswap.v4-hooks-getting-started",
    family: "uniswap",
    title: "Hooks getting started",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/hooks/getting-started`,
    rawHref: `${DOCS}/protocols/v4/guides/hooks/getting-started.md`,
    why: "The Foundry environment, the template and the test routers a hook project starts from.",
    shapes: HOOKS,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 19,
  },
  {
    id: "uniswap.v4-your-first-hook",
    family: "uniswap",
    title: "Your first hook",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/hooks/your-first-hook`,
    rawHref: `${DOCS}/protocols/v4/guides/hooks/your-first-hook.md`,
    why: "A counter hook end to end, permissions, callbacks, mining and tests. The shape every later hook follows.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "core",
    readOrder: 20,
  },
  {
    id: "uniswap.v4-hook-deployment",
    family: "uniswap",
    title: "Hook deployment",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/hooks/hook-deployment`,
    rawHref: `${DOCS}/protocols/v4/guides/hooks/hook-deployment.md`,
    why: "Mine a CREATE2 salt so the address carries the right permission bits, then deploy and verify. A hook at the wrong address reverts on every call.",
    shapes: HOOKS,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 21,
  },
  {
    id: "uniswap.v4-template",
    family: "uniswap",
    title: "v4 hook template",
    kind: "repo",
    href: "https://github.com/uniswapfoundation/v4-template",
    rawHref: "https://raw.githubusercontent.com/uniswapfoundation/v4-template/main/README.md",
    why: "A Foundry project with core, periphery, a mock pool manager, test routers and a sample hook already wired. Start here instead of assembling the dependencies by hand.",
    shapes: V4,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 22,
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.basehook-source",
    family: "uniswap",
    title: "BaseHook.sol",
    kind: "repo",
    href: `${HOOKS_PUBLIC}/src/base/BaseHook.sol`,
    rawHref: `${RAW}/v4-hooks-public/main/src/base/BaseHook.sol`,
    why: "The abstract contract a hook inherits, with the permission declaration and the callback stubs. Overriding the right ones is most of the work.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "core",
    readOrder: 23,
  },
  {
    id: "uniswap.hooks-library-source",
    family: "uniswap",
    title: "Hooks.sol",
    kind: "repo",
    href: `${GH}/v4-core/blob/main/src/libraries/Hooks.sol`,
    rawHref: `${RAW}/v4-core/main/src/libraries/Hooks.sol`,
    why: "The permission flags and how the pool manager decides which callbacks to make. The bits your address must set.",
    shapes: HOOKS,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "uniswap.hookminer-source",
    family: "uniswap",
    title: "HookMiner.sol",
    kind: "repo",
    href: `${HOOKS_PUBLIC}/src/utils/HookMiner.sol`,
    rawHref: `${RAW}/v4-hooks-public/main/src/utils/HookMiner.sol`,
    why: "Finds the salt that gives a hook an address with the required flag bits. Run it in your deploy script and record the salt.",
    shapes: HOOKS,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 24,
  },
  {
    id: "uniswap.v4-swap-hooks",
    family: "uniswap",
    title: "Swap hooks guide",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/hooks/swap-hooks`,
    rawHref: `${DOCS}/protocols/v4/guides/hooks/swap-hooks.md`,
    why: "Before and after swap callbacks, what each receives and what it may change. The place a dynamic fee is set.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-liquidity-hooks",
    family: "uniswap",
    title: "Liquidity hooks guide",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/hooks/liquidity-hooks`,
    rawHref: `${DOCS}/protocols/v4/guides/hooks/liquidity-hooks.md`,
    why: "Callbacks around adding and removing liquidity. Where gating providers and tracking positions happens.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-dynamic-fees",
    family: "uniswap",
    title: "Dynamic fees",
    kind: "docs",
    href: `${DOCS}/protocols/v4/concepts/dynamic-fees`,
    rawHref: `${DOCS}/protocols/v4/concepts/dynamic-fees.md`,
    why: "The dynamic fee flag, updating the fee from a hook and the override on a single swap. The mechanism is provided; the schedule is your product.",
    shapes: HOOKS,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 25,
  },
  {
    id: "uniswap.lpfee-library-source",
    family: "uniswap",
    title: "LPFeeLibrary.sol",
    kind: "repo",
    href: `${GH}/v4-core/blob/main/src/libraries/LPFeeLibrary.sol`,
    rawHref: `${RAW}/v4-core/main/src/libraries/LPFeeLibrary.sol`,
    why: "The dynamic fee flag, the override flag and the maximum fee, as constants. The bounds your schedule must respect.",
    shapes: HOOKS,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-custom-accounting",
    family: "uniswap",
    title: "Custom accounting",
    kind: "docs",
    href: `${DOCS}/protocols/v4/guides/custom-accounting`,
    rawHref: `${DOCS}/protocols/v4/guides/custom-accounting.md`,
    why: "Return deltas from a hook to take a fee, pay a rebate or replace the curve. The most powerful and the most dangerous callback, and the one the security framework singles out.",
    shapes: HOOKS,
    steps: ["architecture", "security"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-security",
    family: "uniswap",
    title: "v4 security framework",
    kind: "docs",
    href: `${DOCS}/protocols/v4/security`,
    rawHref: `${DOCS}/protocols/v4/security.md`,
    why: "The risk categories for hooks, custom accounting, dynamic fees, autonomous parameter changes, external dependencies, upgradeability and liquidity behaviour. Mandatory for any pool with a hook.",
    shapes: V4,
    steps: ["security", "review"],
    priority: "core",
    readOrder: 26,
  },
  {
    id: "uniswap.security-resources",
    family: "uniswap",
    title: "Builder security resources",
    kind: "docs",
    href: `${DOCS}/ecosystem/builder-support/security-resources`,
    rawHref: `${DOCS}/ecosystem/builder-support/security-resources.md`,
    why: "Audit programmes, tooling and reviewers the ecosystem points builders at. Where to look when a hook needs a second pair of eyes.",
    shapes: HOOKS,
    steps: ["security"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-core-audits",
    family: "uniswap",
    title: "v4 core audits",
    kind: "docs",
    href: `${GH}/v4-core/tree/main/docs/security/audits`,
    why: "Every audit of the singleton. Your hook review starts where these ended, on the assumption that the core holds.",
    shapes: V4,
    steps: ["security"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.hooks-public",
    family: "uniswap",
    title: "Public hook implementations",
    kind: "repo",
    href: `${GH}/v4-hooks-public`,
    rawHref: `${RAW}/v4-hooks-public/main/README.md`,
    why: "Production hooks the protocol team maintains, with tests, audits and a simulation study. Real code rather than tutorial code.",
    shapes: HOOKS,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 27,
  },
  {
    id: "uniswap.stable-pair-hook-source",
    family: "uniswap",
    title: "StablePairHook.sol",
    kind: "repo",
    href: `${HOOKS_PUBLIC}/src/stable/StablePairHook.sol`,
    rawHref: `${RAW}/v4-hooks-public/main/src/stable/StablePairHook.sol`,
    why: "A production dynamic-fee hook for assets that should trade near a fixed price. The first hook to study even if your pool is not stable to stable.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.stable-pair-technical",
    family: "uniswap",
    title: "Stable pair hook technical note",
    kind: "docs",
    href: `${HOOKS_PUBLIC}/docs/technical/StablePairHook.md`,
    rawHref: `${RAW}/v4-hooks-public/main/docs/technical/StablePairHook.md`,
    why: "Why the fee moves the way it does, with the price caching and decay that make it safe. A model for writing down your own schedule.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.stable-pair-docs",
    family: "uniswap",
    title: "Stable pair hook overview",
    kind: "docs",
    href: `${DOCS}/protocols/uniswap-labs-hooks/stable-pair/overview`,
    rawHref: `${DOCS}/protocols/uniswap-labs-hooks/stable-pair/overview.md`,
    why: "The docs side of the same hook, with the dynamic fee and fee decay concepts and its own security page.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.stable-pair-dynamic-fees",
    family: "uniswap",
    title: "Stable pair dynamic fees",
    kind: "docs",
    href: `${DOCS}/protocols/uniswap-labs-hooks/stable-pair/concepts/dynamic-fees`,
    rawHref: `${DOCS}/protocols/uniswap-labs-hooks/stable-pair/concepts/dynamic-fees.md`,
    why: "How a shipped hook turns market conditions into a fee. Compare your schedule against it before you commit to one.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.stable-pair-audit",
    family: "uniswap",
    title: "Stable pair hook audit",
    kind: "paper",
    href: `${HOOKS_PUBLIC}/docs/audits/openzeppelin-stablepair.pdf`,
    why: "What an auditor looked for in a production hook. A checklist in disguise for your own.",
    shapes: HOOKS,
    steps: ["security"],
    priority: "deep_dive",
  },
  {
    id: "uniswap.permissioned-pools-docs",
    family: "uniswap",
    title: "Permissioned pools overview",
    kind: "docs",
    href: `${DOCS}/protocols/uniswap-labs-hooks/permissioned-pools/overview`,
    rawHref: `${DOCS}/protocols/uniswap-labs-hooks/permissioned-pools/overview.md`,
    why: "A hook that gates trading and liquidity to an allowlist, with a matching position manager. The pattern for a pool over a transfer-restricted asset.",
    shapes: HOOKS,
    steps: ["architecture"],
    priority: "recommended",
  },

  // -- CanHav liquidity kit files for the pool shapes (M36) ----------------------
  {
    id: "canhav.uniswap-deploy-runbook",
    family: "uniswap",
    title: "Deploy the stack on testnet 46630",
    chains: ["robinhood_testnet"],
    kind: "template",
    href: `${KIT}/DEPLOY_TESTNET_46630.md`,
    rawHref: `${KIT}/DEPLOY_TESTNET_46630.md`,
    why: "The runbook for putting v2 or v4 on testnet yourself, in order, with what to pin and record at every step, because the protocol has no deployment there.",
    shapes: POOLS,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 28,
    flags: ["self_deploy"],
  },
  {
    id: "canhav.uniswap-testnet-manifest-template",
    family: "uniswap",
    title: "Testnet 46630 manifest template (JSON)",
    chains: ["robinhood_testnet"],
    kind: "template",
    href: `${KIT}/robinhood-testnet-46630.manifest.template.json`,
    rawHref: `${KIT}/robinhood-testnet-46630.manifest.template.json`,
    why: "The file your deployment fills in and your config, tests and agent read. Every contract, token and hook as a null until you deploy it, with the commit, compiler and transaction beside each address.",
    shapes: POOLS,
    steps: ["architecture", "reality"],
    priority: "core",
    readOrder: 29,
    flags: ["self_deploy"],
  },
  {
    id: "canhav.uniswap-mainnet-manifest",
    family: "uniswap",
    title: "Mainnet 4663 manifest (CanHav copy)",
    chains: ["robinhood_testnet"],
    kind: "addresses",
    href: `${KIT}/robinhood-mainnet-4663.manifest.json`,
    rawHref: `${KIT}/robinhood-mainnet-4663.manifest.json`,
    why: "The canonical mainnet addresses as one JSON, copied from the protocol's deployment record with the notice first. Reference for a fork, never a value to paste into a testnet config.",
    shapes: POOLS,
    steps: ["reality"],
    priority: "recommended",
    flags: ["mainnet_only"],
  },
  {
    id: "canhav.pool-parameters",
    family: "uniswap",
    title: "Pool parameters worksheet",
    kind: "template",
    href: `${KIT}/POOL_PARAMETERS.md`,
    rawHref: `${KIT}/POOL_PARAMETERS.md`,
    why: "The pool key, the starting price, the first range and the seed amounts as product decisions, one copy per pool, with the v2 ratio and slippage worksheet beside it.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "core",
    readOrder: 30,
  },
  {
    id: "canhav.hook-design",
    family: "uniswap",
    title: "Hook design",
    kind: "template",
    href: `${KIT}/HOOK_DESIGN.md`,
    rawHref: `${KIT}/HOOK_DESIGN.md`,
    why: "The permission flags, a fee schedule worksheet, the custom accounting deltas and the risk categories from the security framework, written down before the first line of the hook.",
    shapes: HOOKS,
    steps: ["architecture", "security"],
    priority: "core",
    readOrder: 31,
  },
  {
    id: "canhav.pool-invariants",
    family: "uniswap",
    title: "Pool invariants",
    kind: "template",
    href: `${KIT}/POOL_INVARIANTS.md`,
    rawHref: `${KIT}/POOL_INVARIANTS.md`,
    why: "Twelve statements that must always hold for a pair, a concentrated pool and a hook, phrased for Foundry, with the ones a hook can break marked.",
    shapes: POOLS,
    steps: ["security"],
    priority: "core",
    readOrder: 32,
  },

  // -- routing, approvals, data --------------------------------------------------
  {
    id: "uniswap.universal-router",
    family: "uniswap",
    title: "Universal Router repository",
    kind: "repo",
    href: `${GH}/universal-router`,
    rawHref: `${RAW}/universal-router/main/README.md`,
    why: "One router for v2, v3 and v4 swaps, Permit2 and wrapping. Deploy it on testnet once your pools exist so users have one entry point.",
    shapes: POOLS,
    steps: ["architecture", "reality"],
    priority: "recommended",
    flags: ["self_deploy"],
  },
  {
    id: "uniswap.universal-router-docs",
    family: "uniswap",
    title: "Universal Router overview",
    kind: "docs",
    href: `${DOCS}/protocols/universal-router/overview`,
    rawHref: `${DOCS}/protocols/universal-router/overview.md`,
    why: "Commands, inputs and the recommendation to target it rather than the older swap routers for any new integration.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.permit2-docs",
    family: "uniswap",
    title: "Permit2 overview",
    kind: "docs",
    href: `${DOCS}/protocols/permit2/overview`,
    rawHref: `${DOCS}/protocols/permit2/overview.md`,
    why: "Signature-based approvals shared across integrations. One approval per token per user, then signatures.",
    shapes: POOLS,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-subgraph",
    family: "uniswap",
    title: "v4 subgraph",
    kind: "repo",
    href: `${GH}/v4-subgraph`,
    rawHref: `${RAW}/v4-subgraph/main/README.md`,
    why: "The official indexer for pools, swaps, positions and fees, with the per-network configuration. Nobody hosts one for testnet 46630, so deploy your own or start from RPC logs.",
    shapes: V4,
    steps: ["architecture"],
    priority: "recommended",
  },
  {
    id: "uniswap.v4-subgraph-entities",
    family: "uniswap",
    title: "v4 subgraph entities",
    kind: "docs",
    href: `${DOCS}/ecosystem/subgraphs/concepts/v4/entities`,
    rawHref: `${DOCS}/ecosystem/subgraphs/concepts/v4/entities.md`,
    why: "The entity model an indexer should end up with, useful even when the first version is a table fed from viem.",
    shapes: V4,
    steps: ["architecture"],
    priority: "deep_dive",
  },
];
